//! HIR → Rust 源码。

use crate::error::{diag, CompileError};
use crate::ir::*;
use swc_common::Span;

mod helpers;

fn emit_json_object_field_get(o: &str, prop: &str, kind: ObjectMemberAccessKind) -> String {
    match kind {
        ObjectMemberAccessKind::NumberLeaf => format!(
            "(({o}).get({prop:?}).expect(\"missing field\").as_f64().expect(\"expected JSON number field\"))"
        ),
        ObjectMemberAccessKind::NestedObject => format!(
            "(({o}).get({prop:?}).expect(\"missing field\").clone())"
        ),
        // R2: Method field - return the method name string wrapped in a special object
        ObjectMemberAccessKind::Method => format!(
            "serde_json::json!({{\"__trust_method\": ({o}).get({prop:?}).expect(\"missing method field\").as_str().expect(\"method field should be string\")}})"
        ),
    }
}

fn emit_object_lit_json(
    fields: &[(String, IRExpr)],
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    if fields.is_empty() {
        return Ok("serde_json::json!({})".to_string());
    }
    let mut parts = Vec::with_capacity(fields.len());
    for (k, v) in fields {
        let k_json = serde_json::to_string(k).map_err(|e| {
            diag(
                f.cm.as_ref(),
                &f.source_path,
                f.span,
                format!("object key JSON encoding: {e}"),
            )
        })?;
        let ve = emit_expr(v, f, stmt_level, module)?;
        parts.push(format!("{k_json}: ({ve})"));
    }
    Ok(format!("serde_json::json!({{{}}})", parts.join(", ")))
}

/// R2: Check if any field is a function reference (for deep chains with methods)
fn has_function_typed_field(fields: &[(String, IRExpr)]) -> bool {
    fields.iter().any(|(_, v)| matches!(v, IRExpr::Ident(..)))
}

/// R2: Emit object literal with function fields
/// For objects with methods, store method names as strings for runtime dispatch
fn emit_object_lit_with_methods(
    fields: &[(String, IRExpr)],
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    let mut parts = Vec::with_capacity(fields.len());
    for (k, v) in fields {
        match v {
            IRExpr::Ident(fn_name, _) => {
                // Store method name as string for runtime dispatch
                parts.push(format!("{k:?}: {fn_name:?}"));
            }
            _ => {
                let ve = emit_expr(v, f, stmt_level, module)?;
                parts.push(format!("{k:?}: ({ve})"));
            }
        }
    }
    Ok(format!("serde_json::json!({{{}}})", parts.join(", ")))
}

/// 代码生成选项中的标准库模式（CLI 兼容保留；**实现均在 `trust_stdlib` crate**，输出与模式无关）。
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum StdlibMode {
    /// 历史别名；生成代码与 `TrustStdlib` 相同。
    Legacy,
    #[default]
    TrustStdlib,
}

#[derive(Debug, Clone, Default)]
pub struct CodegenOptions {
    /// 在每条语句前写入 `// ts: path:line:col`（与诊断格式一致）。
    pub span_comments: bool,
    /// 在语句（及顶层函数）前写入 TS 源码中的 leading 注释（`//` / `/* */` 转为 Rust 行注释）。
    pub emit_ts_source_comments: bool,
    /// 标准库模式（保留 CLI；运行时实现统一在 `trust_stdlib`）。
    pub stdlib_mode: StdlibMode,
}

pub fn emit_rust(module: &IRModule) -> Result<String, CompileError> {
    emit_rust_with_options(module, &CodegenOptions::default())
}

pub fn emit_rust_with_options(
    module: &IRModule,
    opts: &CodegenOptions,
) -> Result<String, CompileError> {
    let _ = opts.stdlib_mode;
    let mut out = String::new();
    out.push_str("// Generated by trust — do not edit by hand.\n\n");

    // R2: Helper function for calling methods on JSON objects with method names stored as strings
    out.push_str("fn __trust_call_method(obj: &serde_json::Value, method: &str) -> serde_json::Value {\n");
    out.push_str("    serde_json::json!({\"__trust_method\": method, \"__trust_receiver\": obj.clone()})\n");
    out.push_str("}\n\n");

    if module_needs_http_stream(module) {
        out.push_str("use futures_util::StreamExt;\n\n#[derive(Clone)]\nstruct __TrustStreamReadResult {\n    done: bool,\n    value: Vec<u8>,\n}\n\n");
    }

    for c in &module.classes {
        let trait_name = format!("{}Dyn", c.name);
        let struct_name = format!("{}Obj", c.name);
        out.push_str(&format!("trait {trait_name} {{\n"));
        out.push_str("    fn __class_name(&self) -> &'static str;\n");
        out.push_str("}\n");
        out.push_str(&format!(
            "struct {struct_name} {{ data: std::collections::HashMap<String, f64> }}\n"
        ));
        out.push_str(&format!("impl {trait_name} for {struct_name} {{\n"));
        out.push_str("    fn __class_name(&self) -> &'static str {\n");
        // `Debug` escaping prevents `"` / `\n` in TS class names from breaking the generated literal.
        out.push_str(&format!("        {:?}\n", c.name));
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    let main_fn = module
        .fns
        .iter()
        .find(|f| f.name == "main")
        .expect("sem ensures main exists");

    for f in &module.fns {
        emit_fn(&mut out, f, 0, opts, module)?;
    }

    if main_fn.is_async {
        out.push_str("#[tokio::main]\nasync fn main() {\n");
    } else {
        out.push_str("fn main() {\n");
    }
    let ret_ty_s = rust_ty(&main_fn.ret, main_fn)?;
    let ret_ty = ret_ty_s.as_str();
    let await_main = if main_fn.is_async { ".await" } else { "" };
    match ret_ty {
        "()" => {
            out.push_str(&format!("    ts_main(){await_main};\n"));
        }
        "f64" | "bool" | "String" => {
            out.push_str(&format!("    println!(\"{{}}\", ts_main(){await_main});\n"));
        }
        "Vec<f64>"
        | "Vec<String>"
        | "Vec<reqwest::Response>"
        | "std::collections::HashMap<String, f64>"
        | "serde_json::Value" => {
            out.push_str(&format!(
                "    println!(\"{{:?}}\", ts_main(){await_main});\n"
            ));
        }
        _ => {
            out.push_str(&format!(
                "    println!(\"{{:?}}\", ts_main(){await_main});\n"
            ));
        }
    }
    out.push_str("}\n");

    Ok(out)
}

fn module_needs_http_stream(module: &IRModule) -> bool {
    module.fns.iter().any(|f| stmts_maybe_http_stream(&f.body))
}

fn stmts_maybe_http_stream(stmts: &[IRStmt]) -> bool {
    stmts.iter().any(|s| match s {
        IRStmt::Let { init, .. } => init.as_ref().is_some_and(expr_maybe_http_stream),
        IRStmt::Assign { rhs, .. } => expr_maybe_http_stream(rhs),
        IRStmt::MemberAssign { rhs, .. } => expr_maybe_http_stream(rhs),
        IRStmt::Expr { expr, .. } => expr_maybe_http_stream(expr),
        IRStmt::Return { arg: Some(e), .. } => expr_maybe_http_stream(e),
        IRStmt::Return { arg: None, .. } => false,
        IRStmt::Block { stmts: b, .. } => stmts_maybe_http_stream(b),
        IRStmt::If {
            cond,
            then_b,
            else_b,
            ..
        } => {
            expr_maybe_http_stream(cond)
                || stmts_maybe_http_stream(then_b)
                || else_b.as_deref().is_some_and(stmts_maybe_http_stream)
        }
        IRStmt::While { cond, body, .. } => {
            expr_maybe_http_stream(cond) || stmts_maybe_http_stream(body)
        }
        IRStmt::ForIn { target, body, .. } => {
            expr_maybe_http_stream(target) || stmts_maybe_http_stream(body)
        }
        IRStmt::DoWhile { body, cond, .. } => {
            stmts_maybe_http_stream(body) || expr_maybe_http_stream(cond)
        }
        IRStmt::FnDecl { func, .. } => stmts_maybe_http_stream(&func.body),
        IRStmt::Empty { .. } | IRStmt::Break { .. } | IRStmt::Continue { .. } => false,
    })
}

fn expr_maybe_http_stream(e: &IRExpr) -> bool {
    match e {
        IRExpr::HttpResponseBodyGetReader { .. } | IRExpr::ReaderRead { .. } => true,
        IRExpr::Await { arg, .. } => expr_maybe_http_stream(arg),
        IRExpr::Binary { left, right, .. } => {
            expr_maybe_http_stream(left) || expr_maybe_http_stream(right)
        }
        IRExpr::Unary { arg, .. } => expr_maybe_http_stream(arg),
        IRExpr::Call { args, .. }
        | IRExpr::OptionalCall { args, .. }
        | IRExpr::BuiltinLog { args, .. }
        | IRExpr::MathBuiltin { args, .. }
        | IRExpr::NumberBuiltin { args, .. }
        | IRExpr::JsonBuiltin { args, .. }
        | IRExpr::UriBuiltin { args, .. } => args.iter().any(expr_maybe_http_stream),
        IRExpr::MethodCall { receiver, args, .. }
        | IRExpr::OptionalMethodCall { receiver, args, .. } => {
            expr_maybe_http_stream(receiver) || args.iter().any(expr_maybe_http_stream)
        }
        IRExpr::StringMethodBuiltin { receiver, args, .. } => {
            expr_maybe_http_stream(receiver) || args.iter().any(expr_maybe_http_stream)
        }
        IRExpr::Conditional {
            test, cons, alt, ..
        } => {
            expr_maybe_http_stream(test)
                || expr_maybe_http_stream(cons)
                || expr_maybe_http_stream(alt)
        }
        IRExpr::Seq { exprs, .. } => exprs.iter().any(expr_maybe_http_stream),
        IRExpr::Tpl { parts, .. } => parts.iter().any(|p| {
            if let TplPart::Interp(x) = p {
                expr_maybe_http_stream(x)
            } else {
                false
            }
        }),
        IRExpr::Member { obj, .. } | IRExpr::OptionalMember { obj, .. } => {
            expr_maybe_http_stream(obj)
        }
        IRExpr::NullishCoalesce { left, right, .. } => {
            expr_maybe_http_stream(left) || expr_maybe_http_stream(right)
        }
        IRExpr::ArrayLit { elems, .. } => elems.iter().any(expr_maybe_http_stream),
        IRExpr::ObjectLit { fields, .. } => fields.iter().any(|(_, v)| expr_maybe_http_stream(v)),
        IRExpr::Index { obj, index, .. } => {
            expr_maybe_http_stream(obj) || expr_maybe_http_stream(index)
        }
        IRExpr::ArrowFn { body, .. } => stmts_maybe_http_stream(body),
        IRExpr::PromiseAll { elems, .. } => elems.iter().any(expr_maybe_http_stream),
        IRExpr::ReadFileText { path, .. } | IRExpr::ReadFileTextAsync { path, .. } => {
            expr_maybe_http_stream(path)
        }
        IRExpr::Fetch { .. }
        | IRExpr::HttpResponseMethodBuiltin { .. }
        | IRExpr::Number(..)
        | IRExpr::Bool(..)
        | IRExpr::Str(..)
        | IRExpr::Ident(..)
        | IRExpr::Null(..)
        | IRExpr::Undefined(..)
        | IRExpr::This(..)
        | IRExpr::Super(..)
        | IRExpr::ReadStdinLine { .. }
        | IRExpr::FetchText { .. }
        | IRExpr::RustNew { .. } => false,
    }
}

fn rust_fn_name(name: &str) -> &str {
    helpers::rust_fn_name(name)
}

fn is_numberish(t: &TsType) -> bool {
    helpers::is_numberish(t)
}

fn is_booleanish(t: &TsType) -> bool {
    helpers::is_booleanish(t)
}

fn is_stringish(t: &TsType) -> bool {
    helpers::is_stringish(t)
}

fn rust_ty(t: &TsType, f: &IRFunction) -> Result<String, CompileError> {
    helpers::rust_ty_string(t, f)
}

fn emit_fn(
    out: &mut String,
    f: &IRFunction,
    level: usize,
    opts: &CodegenOptions,
    module: &IRModule,
) -> Result<(), CompileError> {
    if !f.type_params.is_empty() {
        return Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            f.span,
            format!(
                "internal error: generic function `{}` must be monomorphized before codegen",
                f.name
            ),
        ));
    }
    let ind = indent(level);
    emit_frozen_ts_leading_comments(out, &ind, module, &f.source_path, f.span, opts);
    let name = rust_fn_name(&f.name);
    out.push_str(&ind);
    if f.is_async {
        out.push_str("async ");
    }
    out.push_str("fn ");
    out.push_str(name);
    out.push('(');
    for (i, (p, ty)) in f.params.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(p);
        out.push_str(": ");
        out.push_str(&rust_ty(ty, f)?);
    }
    out.push_str(") -> ");
    out.push_str(&rust_ty(&f.ret, f)?);
    out.push_str(" {\n");
    for s in &f.body {
        emit_stmt(out, s, level + 1, f, opts, module)?;
    }
    out.push_str(&ind);
    out.push_str("}\n");
    if level == 0 {
        out.push('\n');
    }
    Ok(())
}

fn indent(n: usize) -> String {
    helpers::indent(n)
}

fn stmt_span(s: &IRStmt) -> Span {
    helpers::stmt_span(s)
}

fn emit_ts_span_comment(out: &mut String, ind: &str, f: &IRFunction, span: Span) {
    helpers::emit_ts_span_comment(out, ind, f, span);
}

fn emit_frozen_ts_leading_comments(
    out: &mut String,
    ind: &str,
    module: &IRModule,
    source_path: &str,
    span: Span,
    opts: &CodegenOptions,
) {
    if !opts.emit_ts_source_comments {
        return;
    }
    let Some(map) = module.ts_comments_by_path.get(source_path) else {
        return;
    };
    let Some(lines) = map.get(&span.lo().0) else {
        return;
    };
    for line in lines {
        out.push_str(ind);
        out.push_str("// ");
        out.push_str(line);
        out.push('\n');
    }
}

fn emit_stmt(
    out: &mut String,
    s: &IRStmt,
    level: usize,
    f: &IRFunction,
    opts: &CodegenOptions,
    module: &IRModule,
) -> Result<(), CompileError> {
    let ind = indent(level);
    let sp = stmt_span(s);
    emit_frozen_ts_leading_comments(out, &ind, module, &f.source_path, sp, opts);
    if opts.span_comments && !matches!(s, IRStmt::Empty { .. }) {
        emit_ts_span_comment(out, &ind, f, sp);
    }
    match s {
        IRStmt::Empty { .. } => {}
        IRStmt::Let {
            name,
            ty,
            init,
            mutable,
            ..
        } => {
            if *ty == TsType::ReadableStreamDefaultReader {
                if let Some(IRExpr::HttpResponseBodyGetReader {
                    response,
                    stream_slot: Some(slot),
                    ..
                }) = init.as_ref()
                {
                    out.push_str(&ind);
                    out.push_str(&format!("let mut __trust_stream_{slot} = "));
                    out.push_str(&emit_expr(response, f, level, module)?);
                    out.push_str(".bytes_stream();\n");
                    return Ok(());
                }
                return Err(diag(
                    f.cm.as_ref(),
                    &f.source_path,
                    stmt_span(s),
                    "internal error: `ReadableStreamDefaultReader` binding must use `response.body.getReader()` with a stream slot",
                ));
            }
            out.push_str(&ind);
            if *mutable {
                out.push_str("let mut ");
            } else {
                out.push_str("let ");
            }
            out.push_str(name);
            out.push_str(": ");
            out.push_str(&rust_ty(ty, f)?);
            if let Some(init_e) = init {
                out.push_str(" = ");
                out.push_str(&emit_expr(init_e, f, level, module)?);
            }
            out.push_str(";\n");
        }
        IRStmt::Assign { name, rhs, .. } => {
            out.push_str(&ind);
            out.push_str(name);
            out.push_str(" = ");
            out.push_str(&emit_expr(rhs, f, level, module)?);
            out.push_str(";\n");
        }
        IRStmt::MemberAssign { obj, prop, rhs, .. } => {
            out.push_str(&ind);
            let rhs_e = emit_expr(rhs, f, level, module)?;
            out.push_str(&format!(
                "if let Some(__m) = {obj}.as_object_mut() {{ __m.insert({prop:?}.to_string(), serde_json::to_value(&({rhs_e})).expect(\"member assign value\")); }}\n",
            ));
        }
        IRStmt::Expr { expr, .. } => {
            out.push_str(&ind);
            out.push_str(&emit_expr_stmt(expr, f, level, module)?);
            out.push_str(";\n");
        }
        IRStmt::Return { arg, .. } => {
            out.push_str(&ind);
            out.push_str("return ");
            if let Some(e) = arg {
                out.push_str(&emit_expr(e, f, level, module)?);
            }
            out.push_str(";\n");
        }
        IRStmt::Block { stmts, .. } => {
            out.push_str(&ind);
            out.push_str("{\n");
            for x in stmts {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::If {
            cond,
            cond_ty,
            then_b,
            else_b,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("if ");
            let c = emit_expr(cond, f, level, module)?;
            if is_numberish(cond_ty) {
                out.push_str(&format!("({c}) != 0.0"));
            } else {
                out.push_str(&format!("({c})"));
            }
            out.push_str(" {\n");
            for x in then_b {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push('}');
            if let Some(else_b) = else_b {
                out.push_str(" else {\n");
                for x in else_b {
                    emit_stmt(out, x, level + 1, f, opts, module)?;
                }
                out.push_str(&ind);
                out.push_str("}\n");
            } else {
                out.push('\n');
            }
        }
        IRStmt::While {
            cond,
            cond_ty,
            body,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("while ");
            let c = emit_expr(cond, f, level, module)?;
            if is_numberish(cond_ty) {
                out.push_str(&format!("({c}) != 0.0"));
            } else {
                out.push_str(&format!("({c})"));
            }
            out.push_str(" {\n");
            for x in body {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::ForIn {
            key,
            key_ty,
            target,
            kind,
            body,
            span,
        } => {
            let t = emit_expr(target, f, level, module)?;
            let key_rust_ty = rust_ty(key_ty, f)?;
            let tmp = format!("__forin_target_{}", span.lo.0);
            out.push_str(&ind);
            out.push_str(&format!("let {tmp} = {t};\n"));
            match kind {
                Some(ForInKind::ObjectKeys) => {
                    out.push_str(&ind);
                    out.push_str(&format!(
                        "for __k in {tmp}.as_object().expect(\"for..in object\").keys() {{\n",
                    ));
                    out.push_str(&indent(level + 1));
                    out.push_str(&format!("let {key}: {key_rust_ty} = __k.clone();\n"));
                }
                Some(ForInKind::ArrayIndices) => {
                    out.push_str(&ind);
                    out.push_str(&format!("for __i in 0..{tmp}.len() {{\n"));
                    out.push_str(&indent(level + 1));
                    out.push_str(&format!("let {key}: {key_rust_ty} = __i.to_string();\n"));
                }
                None => {
                    return Err(diag(
                        f.cm.as_ref(),
                        &f.source_path,
                        *span,
                        "for..in kind missing from sem",
                    ));
                }
            }
            for x in body {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::DoWhile {
            body,
            cond,
            cond_ty,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("loop {\n");
            for x in body {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            let c = emit_expr(cond, f, level, module)?;
            out.push_str(&indent(level + 1));
            if is_numberish(cond_ty) {
                out.push_str(&format!("if ({c}) == 0 {{ break; }}\n"));
            } else {
                out.push_str(&format!("if !({c}) {{ break; }}\n"));
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::Break { .. } => {
            out.push_str(&ind);
            out.push_str("break;\n");
        }
        IRStmt::Continue { .. } => {
            out.push_str(&ind);
            out.push_str("continue;\n");
        }
        IRStmt::FnDecl { func, .. } => {
            emit_fn(out, func, level, opts, module)?;
        }
    }
    Ok(())
}

fn emit_expr_stmt(
    e: &IRExpr,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    match e {
        IRExpr::BuiltinLog { args, stderr, .. } => {
            emit_builtin_log(args, f, stmt_level, *stderr, module)
        }
        _ => emit_expr(e, f, stmt_level, module),
    }
}

/// `println!`/`eprintln!` format strings are built only from fixed `"{}"` segments; user text is never interpolated into the format template.
fn emit_builtin_log(
    args: &[IRExpr],
    f: &IRFunction,
    stmt_level: usize,
    to_stderr: bool,
    module: &IRModule,
) -> Result<String, CompileError> {
    let stderr_lit = if to_stderr { "true" } else { "false" };
    if args.is_empty() {
        return Ok(format!(
            "trust_stdlib::console::log_joined({stderr_lit}, std::vec::Vec::new())"
        ));
    }
    let mut elems = Vec::with_capacity(args.len());
    for a in args {
        let e = emit_expr(a, f, stmt_level, module)?;
        elems.push(format!("format!(\"{{}}\", ({e}))"));
    }
    Ok(format!(
        "trust_stdlib::console::log_joined({stderr_lit}, vec![{}])",
        elems.join(", ")
    ))
}

fn emit_expr(
    e: &IRExpr,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    match e {
        IRExpr::Number(n, _) => Ok(helpers::rust_f64_literal(*n)),
        IRExpr::Bool(b, _) => Ok(format!("{b}")),
        IRExpr::Str(s, _) => Ok(format!("{:?}.to_string()", s)),
        IRExpr::Null(_) | IRExpr::Undefined(_) => Ok("()".to_string()),
        IRExpr::This(_) => Ok("__self".to_string()),
        IRExpr::Super(_) => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            f.span,
            "`super` expression cannot be emitted directly",
        )),
        IRExpr::Ident(name, _) => Ok(name.clone()),
        IRExpr::Unary { op, arg, .. } => {
            let a = emit_expr(arg, f, stmt_level, module)?;
            match op {
                IRUnaryOp::Neg => Ok(format!("(-({a}))")),
                IRUnaryOp::Not => Ok(format!("!({a})")),
            }
        }
        IRExpr::Binary {
            op,
            left,
            right,
            kind,
            span,
        } => {
            let l = emit_expr(left, f, stmt_level, module)?;
            let r = emit_expr(right, f, stmt_level, module)?;
            use IRBinOp::*;
            let mid = match op {
                Add => {
                    if matches!(kind, Some(BinaryKind::StrConcat)) {
                        format!("format!(\"{{}}{{}}\", {l}, {r})")
                    } else {
                        format!("({l} + {r})")
                    }
                }
                Sub => format!("({l} - {r})"),
                Mul => format!("({l} * {r})"),
                Div => format!("({l} / {r})"),
                Eq => format!("({l} == {r})"),
                Ne => format!("({l} != {r})"),
                Lt => format!("({l} < {r})"),
                Le => format!("({l} <= {r})"),
                Gt => format!("({l} > {r})"),
                Ge => format!("({l} >= {r})"),
                LogicalAnd | LogicalOr => {
                    let (lhs_n, rhs_n) = match kind {
                        Some(BinaryKind::Logical {
                            lhs_number_truthy,
                            rhs_number_truthy,
                        }) => (*lhs_number_truthy, *rhs_number_truthy),
                        _ => {
                            return Err(diag(
                                f.cm.as_ref(),
                                &f.source_path,
                                *span,
                                "`&&` / `||` missing Logical kind (semantic pass bug)",
                            ));
                        }
                    };
                    let ls = if lhs_n { format!("({l} != 0.0)") } else { l };
                    let rs = if rhs_n { format!("({r} != 0.0)") } else { r };
                    match op {
                        LogicalAnd => format!("({ls} && {rs})"),
                        LogicalOr => format!("({ls} || {rs})"),
                        _ => unreachable!(),
                    }
                }
            };
            Ok(mid)
        }
        IRExpr::Call { callee, args, .. } | IRExpr::OptionalCall { callee, args, .. } => {
            let name = rust_fn_name(callee);
            let mut a = Vec::new();
            for x in args {
                a.push(emit_expr(x, f, stmt_level, module)?);
            }
            Ok(format!("{}({})", name, a.join(", ")))
        }
        IRExpr::RustNew {
            rust_fn_path,
            unwrap_result,
            args,
            span,
            ..
        } => {
            if args.len() != 1 {
                return Err(diag(
                    f.cm.as_ref(),
                    &f.source_path,
                    *span,
                    format!(
                        "internal error: RustNew expects 1 argument, got {}",
                        args.len()
                    ),
                ));
            }
            let a0 = emit_expr(&args[0], f, stmt_level, module)?;
            let inner = format!("{rust_fn_path}(&({a0}))");
            if *unwrap_result {
                Ok(format!("({inner}).unwrap()"))
            } else {
                Ok(inner)
            }
        }
        IRExpr::ArrowFn {
            params, ret, body, ..
        } => {
            if params.len() != 1 || !is_numberish(&params[0].1) || !is_numberish(ret) {
                return Err(diag(
                    f.cm.as_ref(),
                    &f.source_path,
                    f.span,
                    "current closure codegen supports only `(number) => number`",
                ));
            }
            let (pname, pty) = &params[0];
            let mut body_out = String::new();
            for s in body {
                emit_stmt(
                    &mut body_out,
                    s,
                    stmt_level + 1,
                    f,
                    &CodegenOptions::default(),
                    module,
                )?;
            }
            Ok(format!(
                "std::rc::Rc::new(move |{}: {}| -> {} {{\n{}{} }})",
                pname,
                rust_ty(pty, f)?,
                rust_ty(ret, f)?,
                body_out,
                indent(stmt_level)
            ))
        }
        IRExpr::MethodCall {
            receiver,
            method: _,
            args,
            inherent_rust: Some(rust_m),
            inherent_rust_str_ref,
            inherent_rust_result_to_string,
            ..
        }
        | IRExpr::OptionalMethodCall {
            receiver,
            method: _,
            args,
            inherent_rust: Some(rust_m),
            inherent_rust_str_ref,
            inherent_rust_result_to_string,
            ..
        } => {
            // R2: Check if this is a method call on a serde_json::Value (deep chains)
            // If the method name ends with __obj, emit direct function call
            let is_obj_method = rust_m.ends_with("__obj");
            let recv = emit_expr(receiver, f, stmt_level, module)?;
            let mut ps: Vec<String> = Vec::new();
            for (i, x) in args.iter().enumerate() {
                let e = emit_expr(x, f, stmt_level, module)?;
                let as_ref = inherent_rust_str_ref
                    .as_ref()
                    .and_then(|v| v.get(i).copied())
                    .unwrap_or(false);
                ps.push(if as_ref {
                    format!("({e}).as_str()")
                } else {
                    e
                });
            }
            let inner = if is_obj_method {
                // R2: For __obj methods on JSON objects, we need to:
                // 1. Extract the method name from the JSON object
                // 2. Call the corresponding global function
                // The method name is stored as a string in the field
                let method_field = rust_m.trim_end_matches("__obj");
                let mut all_args = vec![recv.clone()];
                all_args.extend(ps);
                // Generate inline dispatch based on the expected method name
                // Since we know the method name at compile time, we can call directly
                format!("{method_field}({})", all_args.join(", "))
            } else {
                format!("({recv}).{rust_m}({})", ps.join(", "))
            };
            Ok(if *inherent_rust_result_to_string {
                format!("({inner}).to_string()")
            } else {
                inner
            })
        }
        IRExpr::MethodCall {
            receiver,
            method,
            args,
            inherent_rust: None,
            ..
        }
        | IRExpr::OptionalMethodCall {
            receiver,
            method,
            args,
            inherent_rust: None,
            ..
        } => {
            let name = rust_fn_name(method);
            let mut a = vec![emit_expr(receiver, f, stmt_level, module)?];
            for x in args {
                a.push(emit_expr(x, f, stmt_level, module)?);
            }
            Ok(format!("{}({})", name, a.join(", ")))
        }
        IRExpr::BuiltinLog { span, .. } => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            *span,
            "console.log / console.error / console.debug must be in expression statement position",
        )),
        IRExpr::Conditional {
            test,
            cons,
            alt,
            cond_ty,
            span,
            ..
        } => {
            let ct = cond_ty.as_ref().ok_or_else(|| {
                diag(
                    f.cm.as_ref(),
                    &f.source_path,
                    *span,
                    "ternary condition type not filled by sem",
                )
            })?;
            let c = emit_expr(test, f, stmt_level, module)?;
            let cond_s = if is_numberish(ct) {
                format!("({c}) != 0.0")
            } else {
                format!("({c})")
            };
            let t = emit_expr(cons, f, stmt_level, module)?;
            let a = emit_expr(alt, f, stmt_level, module)?;
            Ok(format!("(if {cond_s} {{ {t} }} else {{ {a} }})"))
        }
        IRExpr::Seq { exprs, span } => emit_seq_expr(exprs, *span, f, stmt_level, module),
        IRExpr::Tpl { parts, .. } => emit_tpl(parts, f, stmt_level, module),
        IRExpr::Member {
            obj,
            prop,
            span: member_span,
            length_dispatch,
            http_response_member,
            stream_read_member,
            object_member_access,
        } => {
            let o = emit_expr(obj, f, stmt_level, module)?;
            if let Some(h) = http_response_member {
                return match h {
                    HttpResponseMember::Status => {
                        Ok(format!("(({o}).status().as_u16() as f64)"))
                    }
                    HttpResponseMember::Ok => Ok(format!("(({o}).status().is_success())")),
                    HttpResponseMember::Body => Err(diag(
                        f.cm.as_ref(),
                        &f.source_path,
                        *member_span,
                        "use `response.body.getReader()` — `response.body` cannot be read as a value alone",
                    )),
                };
            }
            if let Some(sr) = stream_read_member {
                return match sr {
                    StreamReadResultMember::Done => Ok(format!("(({o}).done)")),
                    StreamReadResultMember::Value => Ok(format!("(({o}).value)")),
                };
            }
            if prop == "length" {
                match length_dispatch {
                    Some(MemberLengthDispatch::JsStringUtf16) => {
                        Ok(format!("(({o}.encode_utf16().count() as f64))"))
                    }
                    Some(MemberLengthDispatch::VecLen) => Ok(format!("({o}.len() as f64)")),
                    Some(MemberLengthDispatch::Uint8ArrayLen) => {
                        Ok(format!("({o}.len() as f64)"))
                    }
                    None => {
                        let k = object_member_access.ok_or_else(|| {
                            diag(
                                f.cm.as_ref(),
                                &f.source_path,
                                *member_span,
                                "internal: object `.length` field access missing layout",
                            )
                        })?;
                        Ok(emit_json_object_field_get(&o, prop, k))
                    }
                }
            } else {
                let k = object_member_access.ok_or_else(|| {
                    diag(
                        f.cm.as_ref(),
                        &f.source_path,
                        *member_span,
                        "internal: object member access missing layout",
                    )
                })?;
                Ok(emit_json_object_field_get(&o, prop, k))
            }
        }
        IRExpr::OptionalMember {
            obj,
            prop,
            span: om_span,
            length_dispatch,
            http_response_member,
            stream_read_member,
            object_member_access,
        } => match &**obj {
            IRExpr::Null(_) | IRExpr::Undefined(_) => Ok("()".to_string()),
            _ => {
                let o = emit_expr(obj, f, stmt_level, module)?;
                if let Some(h) = http_response_member {
                    return match h {
                        HttpResponseMember::Status => {
                            Ok(format!("(({o}).status().as_u16() as f64)"))
                        }
                        HttpResponseMember::Ok => Ok(format!("(({o}).status().is_success())")),
                        HttpResponseMember::Body => Err(diag(
                            f.cm.as_ref(),
                            &f.source_path,
                            *om_span,
                            "use `response.body.getReader()` — `response.body` cannot be read as a value alone",
                        )),
                    };
                }
                if let Some(sr) = stream_read_member {
                    return match sr {
                        StreamReadResultMember::Done => Ok(format!("(({o}).done)")),
                        StreamReadResultMember::Value => Ok(format!("(({o}).value)")),
                    };
                }
                if prop == "length" {
                    match length_dispatch {
                        Some(MemberLengthDispatch::JsStringUtf16) => {
                            Ok(format!("(({o}.encode_utf16().count() as f64))"))
                        }
                        Some(MemberLengthDispatch::VecLen) => Ok(format!("({o}.len() as f64)")),
                        Some(MemberLengthDispatch::Uint8ArrayLen) => {
                            Ok(format!("({o}.len() as f64)"))
                        }
                        None => {
                            let k = object_member_access.ok_or_else(|| {
                                diag(
                                    f.cm.as_ref(),
                                    &f.source_path,
                                    *om_span,
                                    "internal: object `.length` field access missing layout",
                                )
                            })?;
                            Ok(emit_json_object_field_get(&o, prop, k))
                        }
                    }
                } else {
                    let k = object_member_access.ok_or_else(|| {
                        diag(
                            f.cm.as_ref(),
                            &f.source_path,
                            *om_span,
                            "internal: object member access missing layout",
                        )
                    })?;
                    Ok(emit_json_object_field_get(&o, prop, k))
                }
            }
        },
        IRExpr::MathBuiltin { kind, args, .. } => {
            use MathBuiltinKind::*;
            match kind {
                Abs => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("trust_stdlib::math::abs({a})"))
                }
                Min => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    let b = emit_expr(&args[1], f, stmt_level, module)?;
                    Ok(format!("trust_stdlib::math::min({a}, {b})"))
                }
                Max => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    let b = emit_expr(&args[1], f, stmt_level, module)?;
                    Ok(format!("trust_stdlib::math::max({a}, {b})"))
                }
                Floor => {
                    let n = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("trust_stdlib::math::floor({n})"))
                }
                Ceil => {
                    let n = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("trust_stdlib::math::ceil({n})"))
                }
                Trunc => {
                    let n = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("trust_stdlib::math::trunc({n})"))
                }
                Round => {
                    let n = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("trust_stdlib::math::round({n})"))
                }
                Sign => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("trust_stdlib::math::sign({a})"))
                }
                Pow => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    let b = emit_expr(&args[1], f, stmt_level, module)?;
                    Ok(format!("trust_stdlib::math::pow({a}, {b})"))
                }
            }
        }
        IRExpr::NumberBuiltin { kind, args, .. } => {
            use NumberBuiltinKind::*;
            match kind {
                ParseInt => {
                    let s = emit_expr(&args[0], f, stmt_level, module)?;
                    if args.len() == 1 {
                        Ok(format!("trust_stdlib::number::parse_int_trim(&({s}))"))
                    } else {
                        let radix = emit_expr(&args[1], f, stmt_level, module)?;
                        Ok(format!(
                            "trust_stdlib::number::parse_int_radix(&({s}), ({radix}) as u32)"
                        ))
                    }
                }
                ParseFloat => {
                    let s = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("trust_stdlib::number::parse_float_trim(&({s}))"))
                }
            }
        }
        IRExpr::JsonBuiltin {
            kind,
            args,
            span,
            stringify_inferred_ty,
        } => match kind {
            JsonBuiltinKind::Stringify => {
                let inner = emit_expr(&args[0], f, stmt_level, module)?;
                let ty = stringify_inferred_ty.as_ref().ok_or_else(|| {
                    diag(
                        f.cm.as_ref(),
                        &f.source_path,
                        *span,
                        "JSON.stringify: missing inferred type (sem bug)",
                    )
                })?;
                if is_stringish(ty) {
                    Ok(format!("trust_stdlib::json::escape_string(&({inner}))"))
                } else if is_numberish(ty) || is_booleanish(ty) {
                    Ok(format!("format!(\"{{}}\", {inner})"))
                } else if matches!(ty, TsType::ObjectNum(_)) {
                    Ok(format!(
                        "serde_json::to_string(&({inner})).expect(\"JSON.stringify object\")"
                    ))
                } else {
                    Err(diag(
                        f.cm.as_ref(),
                        &f.source_path,
                        *span,
                        "JSON.stringify: unsupported type for codegen",
                    ))
                }
            }
            JsonBuiltinKind::Parse => {
                let s = emit_expr(&args[0], f, stmt_level, module)?;
                Ok(format!("trust_stdlib::json::parse_number(&({s}))"))
            }
        },
        IRExpr::UriBuiltin { kind, args, .. } => {
            let s = emit_expr(&args[0], f, stmt_level, module)?;
            match kind {
                UriBuiltinKind::EncodeComponent => {
                    Ok(format!("trust_stdlib::uri::encode_component(&({s}))"))
                }
                UriBuiltinKind::DecodeComponent => {
                    Ok(format!("trust_stdlib::uri::decode_component(&({s}))"))
                }
            }
        },
        IRExpr::StringMethodBuiltin {
            kind,
            receiver,
            args,
            span,
        } => emit_string_method_builtin(kind, receiver, args, *span, f, stmt_level, module),
        IRExpr::ReadStdinLine { .. } => Ok("trust_stdlib::io::read_stdin_line()".to_string()),
        IRExpr::ReadFileText { path, .. } => {
            let p = emit_expr(path, f, stmt_level, module)?;
            Ok(format!(
                "trust_stdlib::io::read_file_text(({p}).as_str())"
            ))
        },
        IRExpr::ReadFileTextAsync { path, .. } => {
            let p = emit_expr(path, f, stmt_level, module)?;
            Ok(format!(
                "trust_stdlib::io::read_file_text_async(({p}).as_str())"
            ))
        },
        IRExpr::NullishCoalesce { left, right, .. } => {
            if matches!(&**left, IRExpr::Null(_) | IRExpr::Undefined(_)) {
                emit_expr(right, f, stmt_level, module)
            } else {
                emit_expr(left, f, stmt_level, module)
            }
        }
        IRExpr::ArrayLit { elems, .. } => {
            let mut xs = Vec::with_capacity(elems.len());
            for e in elems {
                xs.push(emit_expr(e, f, stmt_level, module)?);
            }
            Ok(format!("vec![{}]", xs.join(", ")))
        }
        IRExpr::ObjectLit { fields, .. } => {
            // R2: Check if any field is function-typed
            if has_function_typed_field(fields) {
                emit_object_lit_with_methods(fields, f, stmt_level, module)
            } else {
                emit_object_lit_json(fields, f, stmt_level, module)
            }
        }
        IRExpr::Index {
            obj,
            index,
            index_kind,
            ..
        } => {
            let o = emit_expr(obj, f, stmt_level, module)?;
            let i = emit_expr(index, f, stmt_level, module)?;
            match index_kind {
                Some(IndexKind::StringUtf16) => Ok(format!(
                    "({{ let __s = &({o}); let __ii = ({i}) as i32; let __v: Vec<u16> = __s.encode_utf16().collect(); let __len = __v.len() as i32; let __j = if __ii < 0 {{ __len + __ii }} else {{ __ii }}; if __j < 0 || __j >= __len {{ String::new() }} else {{ String::from_utf16_lossy(&[__v[__j as usize]]) }} }})"
                )),
                Some(IndexKind::ArrayStringElem) => {
                    Ok(format!("({o}[({i}) as usize]).clone()"))
                }
                _ => Ok(format!("({o}[({i}) as usize])")),
            }
        }
        IRExpr::FetchText { url, .. } => {
            let u = emit_expr(url, f, stmt_level, module)?;
            Ok(format!("trust_stdlib::http::fetch_text({u})"))
        }
        IRExpr::Fetch { url, init, .. } => emit_fetch_call(url, init, f, stmt_level, module),
        IRExpr::HttpResponseMethodBuiltin { span, .. } => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            *span,
            "use `await response.text()`, `await response.json()`, or `await reader.read()` on the promise from `fetch` / stream reader",
        )),
        IRExpr::HttpResponseBodyGetReader { span, .. } => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            *span,
            "use `let reader = response.body.getReader()` then `await reader.read()` in a loop",
        )),
        IRExpr::ReaderRead { span, .. } => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            *span,
            "use `await reader.read()` (must be under `await`)",
        )),
        IRExpr::PromiseAll { elems, .. } => {
            let mut parts = Vec::with_capacity(elems.len());
            for e in elems {
                let s = emit_expr(e, f, stmt_level, module)?;
                parts.push(format!("({s}).await"));
            }
            Ok(format!("vec![{}]", parts.join(", ")))
        }
        IRExpr::Await { arg, .. } => match &**arg {
            IRExpr::ReadFileTextAsync { path, .. } => {
                let p = emit_expr(path, f, stmt_level, module)?;
                Ok(format!(
                    "trust_stdlib::io::read_file_text_async(({p}).as_str()).await"
                ))
            }
            IRExpr::HttpResponseMethodBuiltin {
                kind,
                receiver,
                ..
            } => {
                let r = emit_expr(receiver, f, stmt_level, module)?;
                match kind {
                    HttpResponseMethodKind::Text => Ok(format!(
                        "({r}).text().await.expect(\"read body failed\")"
                    )),
                    HttpResponseMethodKind::Json => Ok(format!(
                        "trust_stdlib::json::parse_number(&(({r}).text().await.expect(\"read body failed\")))"
                    )),
                }
            }
            IRExpr::ReaderRead {
                reader_slot: Some(slot),
                ..
            } => Ok(format!(
                "(match __trust_stream_{slot}.next().await {{ std::option::Option::None => __TrustStreamReadResult {{ done: true, value: std::vec::Vec::new() }}, std::option::Option::Some(std::result::Result::Ok(b)) => __TrustStreamReadResult {{ done: false, value: b.to_vec() }}, std::option::Option::Some(std::result::Result::Err(_e)) => panic!(\"read body failed\") }})"
            )),
            IRExpr::ReaderRead { span, .. } => Err(diag(
                f.cm.as_ref(),
                &f.source_path,
                *span,
                "internal error: reader stream slot missing in codegen",
            )),
            _ => {
                let inner = emit_expr(arg, f, stmt_level, module)?;
                Ok(format!("({inner}).await"))
            }
        },
    }
}

fn fetch_init_needs_some(init: &Option<FetchInit>) -> bool {
    init.as_ref()
        .is_some_and(|i| i.method.is_some() || !i.headers.is_empty() || i.body.is_some())
}

fn emit_fetch_call(
    url: &IRExpr,
    init: &Option<FetchInit>,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    let u = emit_expr(url, f, stmt_level, module)?;
    if !fetch_init_needs_some(init) {
        return Ok(format!(
            "trust_stdlib::http::fetch({u}, std::option::Option::None)"
        ));
    }
    let i = init.as_ref().expect("checked");
    let method = i.method.clone().unwrap_or_else(|| "GET".to_string());
    let mut header_parts = Vec::with_capacity(i.headers.len());
    for (k, v) in &i.headers {
        header_parts.push(format!("({:?}.to_string(), {:?}.to_string())", k, v));
    }
    let headers_joined = header_parts.join(", ");
    let body_rust = match &i.body {
        None => "std::option::Option::None".to_string(),
        Some(b) => {
            let be = emit_expr(b, f, stmt_level, module)?;
            format!("std::option::Option::Some(({be}).to_string())")
        }
    };
    Ok(format!(
        "trust_stdlib::http::fetch({u}, std::option::Option::Some(trust_stdlib::http::FetchInit {{ method: {:?}.to_string(), headers: vec![{headers_joined}], body: {body_rust} }}))",
        method
    ))
}

fn emit_string_method_builtin(
    kind: &StringMethodKind,
    receiver: &IRExpr,
    args: &[IRExpr],
    _span: Span,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    let recv = emit_expr(receiver, f, stmt_level, module)?;
    use StringMethodKind::*;
    match kind {
        Length => Ok(format!("trust_stdlib::string::utf16_len(&({recv}))")),
        CharAt => {
            let i = emit_expr(&args[0], f, stmt_level, module)?;
            Ok(format!(
                "({{ let __s = &({recv}); let __ii = ({i}) as i32; let __v: Vec<u16> = __s.encode_utf16().collect(); let __len = __v.len() as i32; let __j = if __ii < 0 {{ __len + __ii }} else {{ __ii }}; if __j < 0 || __j >= __len {{ String::new() }} else {{ String::from_utf16_lossy(&[__v[__j as usize]]) }} }})"
            ))
        }
        CharCodeAt => {
            let i = emit_expr(&args[0], f, stmt_level, module)?;
            Ok(format!(
                "({{ let __s = &({recv}); let __ii = ({i}) as i32; let __v: Vec<u16> = __s.encode_utf16().collect(); let __len = __v.len() as i32; let __j = if __ii < 0 {{ __len + __ii }} else {{ __ii }}; if __j < 0 || __j >= __len {{ 0.0_f64 }} else {{ __v[__j as usize] as f64 }} }})"
            ))
        }
        Slice => {
            let a0 = emit_expr(&args[0], f, stmt_level, module)?;
            if args.len() == 1 {
                Ok(format!(
                    "trust_stdlib::string::utf16_slice(&({recv}), ({a0}) as i32, None, false)"
                ))
            } else {
                let a1 = emit_expr(&args[1], f, stmt_level, module)?;
                Ok(format!(
                    "trust_stdlib::string::utf16_slice(&({recv}), ({a0}) as i32, Some(({a1}) as i32), false)"
                ))
            }
        }
        Substring => {
            let a0 = emit_expr(&args[0], f, stmt_level, module)?;
            if args.len() == 1 {
                Ok(format!(
                    "trust_stdlib::string::utf16_slice(&({recv}), ({a0}) as i32, None, true)"
                ))
            } else {
                let a1 = emit_expr(&args[1], f, stmt_level, module)?;
                Ok(format!(
                    "trust_stdlib::string::utf16_slice(&({recv}), ({a0}) as i32, Some(({a1}) as i32), true)"
                ))
            }
        }
        IndexOf => {
            let needle = emit_expr(&args[0], f, stmt_level, module)?;
            let from = if args.len() == 1 {
                "0i32".to_string()
            } else {
                emit_expr(&args[1], f, stmt_level, module)?
            };
            Ok(format!(
                "trust_stdlib::string::utf16_index_of(&({recv}), &({needle}), ({from}) as i32)"
            ))
        }
        Includes => {
            let needle = emit_expr(&args[0], f, stmt_level, module)?;
            let from = if args.len() == 1 {
                "0i32".to_string()
            } else {
                emit_expr(&args[1], f, stmt_level, module)?
            };
            Ok(format!(
                "(trust_stdlib::string::utf16_index_of(&({recv}), &({needle}), ({from}) as i32) >= 0.0)"
            ))
        }
    }
}

fn emit_seq_expr(
    exprs: &[IRExpr],
    span: Span,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    if exprs.is_empty() {
        return Err(diag(f.cm.as_ref(), &f.source_path, span, "empty sequence"));
    }
    if exprs.len() == 1 {
        return emit_expr(&exprs[0], f, stmt_level, module);
    }
    let inner = indent(stmt_level + 1);
    let close = indent(stmt_level);
    let mut block = String::new();
    block.push_str("({\n");
    for e in &exprs[..exprs.len() - 1] {
        block.push_str(&inner);
        block.push_str(&emit_expr_stmt(e, f, stmt_level, module)?);
        block.push_str(";\n");
    }
    block.push_str(&inner);
    block.push_str(&emit_expr(&exprs[exprs.len() - 1], f, stmt_level, module)?);
    block.push('\n');
    block.push_str(&close);
    block.push_str("})");
    Ok(block)
}

fn emit_tpl(
    parts: &[TplPart],
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    if parts.is_empty() {
        return Ok("\"\".to_string()".to_string());
    }
    if parts.len() == 1 {
        if let TplPart::Static(s) = &parts[0] {
            return Ok(format!("{:?}.to_string()", s));
        }
    }
    let mut fmt = String::new();
    let mut args: Vec<String> = Vec::new();
    for p in parts {
        match p {
            TplPart::Static(s) => {
                for ch in s.chars() {
                    match ch {
                        '{' => fmt.push_str("{{"),
                        '}' => fmt.push_str("}}"),
                        _ => fmt.push(ch),
                    }
                }
            }
            TplPart::Interp(e) => {
                fmt.push_str("{}");
                args.push(emit_expr(e, f, stmt_level, module)?);
            }
        }
    }
    let fmt_esc = fmt.replace('\\', "\\\\").replace('"', "\\\"");
    if args.is_empty() {
        return Ok(format!("format!(\"{fmt_esc}\")"));
    }
    Ok(format!("format!(\"{fmt_esc}\", {})", args.join(", ")))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::build::build_module;
    use crate::sem::check_module;
    use trust_parser::parse_typescript_file;

    #[test]
    fn emit_rust_contains_ts_main_and_println() {
        let src = r#"function main(): number { return 42; }"#;
        let p = parse_typescript_file("t.ts", src).unwrap();
        let mut m = build_module(&p.program, &p.source_map, "t.ts", Some(&p.comments)).unwrap();
        check_module(&mut m).unwrap();
        let rs = emit_rust_with_options(&m, &CodegenOptions::default()).unwrap();
        assert!(rs.contains("fn ts_main"), "{rs}");
        assert!(rs.contains("println!"), "{rs}");
    }

    #[test]
    fn emit_rust_stdlib_helpers_when_needed() {
        let src = r#"function main(): number {
  return "ab".slice(0, 1).length + JSON.stringify(1).length;
}"#;
        let p = parse_typescript_file("t.ts", src).unwrap();
        let mut m = build_module(&p.program, &p.source_map, "t.ts", Some(&p.comments)).unwrap();
        check_module(&mut m).unwrap();
        let rs = emit_rust_with_options(&m, &CodegenOptions::default()).unwrap();
        assert!(rs.contains("trust_stdlib::string::utf16_slice"), "{rs}");
        assert!(rs.contains("trust_stdlib::"), "{rs}");
    }

    #[test]
    fn emit_ts_source_comments_writes_frozen_leading() {
        let src = r#"// __hdr__
function main(): number {
  // __body__
  let x: number = 1;
  return x;
}
"#;
        let p = parse_typescript_file("t.ts", src).unwrap();
        let mut m = build_module(&p.program, &p.source_map, "t.ts", Some(&p.comments)).unwrap();
        check_module(&mut m).unwrap();
        let opts = CodegenOptions {
            emit_ts_source_comments: true,
            ..Default::default()
        };
        let rs = emit_rust_with_options(&m, &opts).unwrap();
        assert!(
            rs.contains("// __hdr__"),
            "expected function-level TS comment in Rust: {rs}"
        );
        assert!(
            rs.contains("// __body__"),
            "expected statement-level TS comment in Rust: {rs}"
        );
    }
}
