//! HIR → Rust 源码。

use crate::error::{diag, CompileError};
use crate::ir::*;
use swc_common::Span;

/// 代码生成选项（默认不改变既有输出）。
#[derive(Debug, Clone, Default)]
pub struct CodegenOptions {
    /// 在每条语句前写入 `// ts: path:line:col`（与诊断格式一致）。
    pub span_comments: bool,
}

pub fn emit_rust(module: &IRModule) -> Result<String, CompileError> {
    emit_rust_with_options(module, &CodegenOptions::default())
}

pub fn emit_rust_with_options(
    module: &IRModule,
    opts: &CodegenOptions,
) -> Result<String, CompileError> {
    let mut out = String::new();
    out.push_str("// Generated by ts2rs — do not edit by hand.\n\n");

    let main_fn = module
        .fns
        .iter()
        .find(|f| f.name == "main")
        .expect("sem ensures main exists");

    for f in &module.fns {
        emit_fn(&mut out, f, 0, opts)?;
    }

    out.push_str("fn main() {\n");
    let ret_ty = rust_ty(&main_fn.ret, main_fn)?;
    match ret_ty {
        "()" => {
            out.push_str("    ts_main();\n");
        }
        "i32" | "bool" | "String" => {
            out.push_str("    println!(\"{}\", ts_main());\n");
        }
        "Vec<i32>" | "std::collections::HashMap<String, i32>" => {
            out.push_str("    println!(\"{:?}\", ts_main());\n");
        }
        _ => {
            return Err(diag(
                main_fn.cm.as_ref(),
                &main_fn.source_path,
                main_fn.span,
                "unexpected return type classification in codegen",
            ));
        }
    }
    out.push_str("}\n");

    Ok(out)
}

fn rust_fn_name(name: &str) -> &str {
    if name == "main" {
        "ts_main"
    } else {
        name
    }
}

fn is_numberish(t: &TsType) -> bool {
    match t {
        TsType::Number | TsType::NumberLit(_) => true,
        TsType::Union(m) => m.iter().all(is_numberish),
        _ => false,
    }
}

fn rust_ty_scalar(t: &TsType) -> &'static str {
    match t {
        TsType::Number | TsType::NumberLit(_) => "i32",
        TsType::Boolean | TsType::BoolLit(_) => "bool",
        TsType::String | TsType::StringLit(_) => "String",
        TsType::Void => "()",
        TsType::Null => "()",
        TsType::Undefined => "()",
        TsType::ArrayNumber => "Vec<i32>",
        TsType::ObjectNum(_) => "std::collections::HashMap<String, i32>",
        TsType::Union(_) => unreachable!("rust_ty_scalar: use rust_ty for unions"),
    }
}

fn rust_ty(t: &TsType, f: &IRFunction) -> Result<&'static str, CompileError> {
    match t {
        TsType::Union(members) => {
            if members.is_empty() {
                return Err(diag(
                    f.cm.as_ref(),
                    &f.source_path,
                    f.span,
                    "empty union type",
                ));
            }
            let mut it = members.iter();
            let first = rust_ty(it.next().unwrap(), f)?;
            for m in it {
                let r = rust_ty(m, f)?;
                if r != first {
                    return Err(diag(
                        f.cm.as_ref(),
                        &f.source_path,
                        f.span,
                        "union type cannot be mapped to a single Rust type (heterogeneous members)",
                    ));
                }
            }
            Ok(first)
        }
        _ => Ok(rust_ty_scalar(t)),
    }
}

fn emit_fn(
    out: &mut String,
    f: &IRFunction,
    level: usize,
    opts: &CodegenOptions,
) -> Result<(), CompileError> {
    let ind = indent(level);
    let name = rust_fn_name(&f.name);
    out.push_str(&ind);
    out.push_str("fn ");
    out.push_str(name);
    out.push('(');
    for (i, (p, ty)) in f.params.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(p);
        out.push_str(": ");
        out.push_str(rust_ty(ty, f)?);
    }
    out.push_str(") -> ");
    out.push_str(rust_ty(&f.ret, f)?);
    out.push_str(" {\n");
    for s in &f.body {
        emit_stmt(out, s, level + 1, f, opts)?;
    }
    out.push_str(&ind);
    out.push_str("}\n");
    if level == 0 {
        out.push('\n');
    }
    Ok(())
}

fn indent(n: usize) -> String {
    "    ".repeat(n)
}

fn stmt_span(s: &IRStmt) -> Span {
    match s {
        IRStmt::Empty { span }
        | IRStmt::Let { span, .. }
        | IRStmt::Assign { span, .. }
        | IRStmt::Expr { span, .. }
        | IRStmt::Return { span, .. }
        | IRStmt::Block { span, .. }
        | IRStmt::If { span, .. }
        | IRStmt::While { span, .. }
        | IRStmt::DoWhile { span, .. }
        | IRStmt::Break { span }
        | IRStmt::Continue { span }
        | IRStmt::FnDecl { span, .. } => *span,
    }
}

fn emit_ts_span_comment(out: &mut String, ind: &str, f: &IRFunction, span: Span) {
    let loc = f.cm.lookup_char_pos(span.lo);
    out.push_str(ind);
    out.push_str("// ts: ");
    out.push_str(&f.source_path);
    out.push(':');
    out.push_str(&loc.line.to_string());
    out.push(':');
    out.push_str(&loc.col_display.to_string());
    out.push('\n');
}

fn emit_stmt(
    out: &mut String,
    s: &IRStmt,
    level: usize,
    f: &IRFunction,
    opts: &CodegenOptions,
) -> Result<(), CompileError> {
    let ind = indent(level);
    if opts.span_comments && !matches!(s, IRStmt::Empty { .. }) {
        emit_ts_span_comment(out, &ind, f, stmt_span(s));
    }
    match s {
        IRStmt::Empty { .. } => {}
        IRStmt::Let {
            name,
            ty,
            init,
            mutable,
            ..
        } => {
            out.push_str(&ind);
            if *mutable {
                out.push_str("let mut ");
            } else {
                out.push_str("let ");
            }
            out.push_str(name);
            out.push_str(": ");
            out.push_str(rust_ty(ty, f)?);
            if let Some(init_e) = init {
                out.push_str(" = ");
                out.push_str(&emit_expr(init_e, f, level)?);
            }
            out.push_str(";\n");
        }
        IRStmt::Assign { name, rhs, .. } => {
            out.push_str(&ind);
            out.push_str(name);
            out.push_str(" = ");
            out.push_str(&emit_expr(rhs, f, level)?);
            out.push_str(";\n");
        }
        IRStmt::Expr { expr, .. } => {
            out.push_str(&ind);
            out.push_str(&emit_expr_stmt(expr, f, level)?);
            out.push_str(";\n");
        }
        IRStmt::Return { arg, .. } => {
            out.push_str(&ind);
            out.push_str("return ");
            if let Some(e) = arg {
                out.push_str(&emit_expr(e, f, level)?);
            }
            out.push_str(";\n");
        }
        IRStmt::Block { stmts, .. } => {
            out.push_str(&ind);
            out.push_str("{\n");
            for x in stmts {
                emit_stmt(out, x, level + 1, f, opts)?;
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::If {
            cond,
            cond_ty,
            then_b,
            else_b,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("if ");
            let c = emit_expr(cond, f, level)?;
            if is_numberish(cond_ty) {
                out.push_str(&format!("({c}) != 0"));
            } else {
                out.push_str(&format!("({c})"));
            }
            out.push_str(" {\n");
            for x in then_b {
                emit_stmt(out, x, level + 1, f, opts)?;
            }
            out.push_str(&ind);
            out.push('}');
            if let Some(else_b) = else_b {
                out.push_str(" else {\n");
                for x in else_b {
                    emit_stmt(out, x, level + 1, f, opts)?;
                }
                out.push_str(&ind);
                out.push_str("}\n");
            } else {
                out.push('\n');
            }
        }
        IRStmt::While {
            cond,
            cond_ty,
            body,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("while ");
            let c = emit_expr(cond, f, level)?;
            if is_numberish(cond_ty) {
                out.push_str(&format!("({c}) != 0"));
            } else {
                out.push_str(&format!("({c})"));
            }
            out.push_str(" {\n");
            for x in body {
                emit_stmt(out, x, level + 1, f, opts)?;
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::DoWhile {
            body,
            cond,
            cond_ty,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("loop {\n");
            for x in body {
                emit_stmt(out, x, level + 1, f, opts)?;
            }
            let c = emit_expr(cond, f, level)?;
            out.push_str(&indent(level + 1));
            if is_numberish(cond_ty) {
                out.push_str(&format!("if ({c}) == 0 {{ break; }}\n"));
            } else {
                out.push_str(&format!("if !({c}) {{ break; }}\n"));
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::Break { .. } => {
            out.push_str(&ind);
            out.push_str("break;\n");
        }
        IRStmt::Continue { .. } => {
            out.push_str(&ind);
            out.push_str("continue;\n");
        }
        IRStmt::FnDecl { func, .. } => {
            emit_fn(out, func, level, opts)?;
        }
    }
    Ok(())
}

fn emit_expr_stmt(e: &IRExpr, f: &IRFunction, stmt_level: usize) -> Result<String, CompileError> {
    match e {
        IRExpr::BuiltinLog { args, stderr, .. } => emit_builtin_log(args, f, stmt_level, *stderr),
        _ => emit_expr(e, f, stmt_level),
    }
}

fn emit_builtin_log(
    args: &[IRExpr],
    f: &IRFunction,
    stmt_level: usize,
    to_stderr: bool,
) -> Result<String, CompileError> {
    let mac = if to_stderr { "eprintln!" } else { "println!" };
    if args.is_empty() {
        return Ok(format!("{mac}()"));
    }
    let mut parts = Vec::new();
    for a in args {
        parts.push(emit_expr(a, f, stmt_level)?);
    }
    if parts.len() == 1 {
        return Ok(format!("{mac}(\"{{}}\", {})", parts[0]));
    }
    let fmt_str = std::iter::repeat("{}")
        .take(parts.len())
        .collect::<Vec<_>>()
        .join(" ");
    let joined = parts.join(", ");
    Ok(format!("{mac}(\"{fmt_str}\", {joined})"))
}

fn emit_expr(e: &IRExpr, f: &IRFunction, stmt_level: usize) -> Result<String, CompileError> {
    match e {
        IRExpr::Number(n, _) => Ok(format!("{n}")),
        IRExpr::Bool(b, _) => Ok(format!("{b}")),
        IRExpr::Str(s, _) => Ok(format!("{:?}.to_string()", s)),
        IRExpr::Null(_) | IRExpr::Undefined(_) => Ok("()".to_string()),
        IRExpr::Ident(name, _) => Ok(name.clone()),
        IRExpr::Unary { op, arg, .. } => {
            let a = emit_expr(arg, f, stmt_level)?;
            match op {
                IRUnaryOp::Neg => Ok(format!("(-({a}))")),
                IRUnaryOp::Not => Ok(format!("!({a})")),
            }
        }
        IRExpr::Binary {
            op,
            left,
            right,
            kind,
            span,
        } => {
            let l = emit_expr(left, f, stmt_level)?;
            let r = emit_expr(right, f, stmt_level)?;
            use IRBinOp::*;
            let mid = match op {
                Add => {
                    if matches!(kind, Some(BinaryKind::StrConcat)) {
                        format!("format!(\"{{}}{{}}\", {l}, {r})")
                    } else {
                        format!("({l} + {r})")
                    }
                }
                Sub => format!("({l} - {r})"),
                Mul => format!("({l} * {r})"),
                Div => format!("({l} / {r})"),
                Eq => format!("({l} == {r})"),
                Ne => format!("({l} != {r})"),
                Lt => format!("({l} < {r})"),
                Le => format!("({l} <= {r})"),
                Gt => format!("({l} > {r})"),
                Ge => format!("({l} >= {r})"),
                LogicalAnd | LogicalOr => {
                    let (lhs_n, rhs_n) = match kind {
                        Some(BinaryKind::Logical {
                            lhs_number_truthy,
                            rhs_number_truthy,
                        }) => (*lhs_number_truthy, *rhs_number_truthy),
                        _ => {
                            return Err(diag(
                                f.cm.as_ref(),
                                &f.source_path,
                                *span,
                                "`&&` / `||` missing Logical kind (semantic pass bug)",
                            ));
                        }
                    };
                    let ls = if lhs_n { format!("({l} != 0)") } else { l };
                    let rs = if rhs_n { format!("({r} != 0)") } else { r };
                    match op {
                        LogicalAnd => format!("({ls} && {rs})"),
                        LogicalOr => format!("({ls} || {rs})"),
                        _ => unreachable!(),
                    }
                }
            };
            Ok(mid)
        }
        IRExpr::Call { callee, args, .. } => {
            let name = rust_fn_name(callee);
            let mut a = Vec::new();
            for x in args {
                a.push(emit_expr(x, f, stmt_level)?);
            }
            Ok(format!("{}({})", name, a.join(", ")))
        }
        IRExpr::MethodCall {
            receiver,
            method,
            args,
            ..
        } => {
            let name = rust_fn_name(method);
            let mut a = vec![emit_expr(receiver, f, stmt_level)?];
            for x in args {
                a.push(emit_expr(x, f, stmt_level)?);
            }
            Ok(format!("{}({})", name, a.join(", ")))
        }
        IRExpr::BuiltinLog { span, .. } => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            *span,
            "console.log / console.error / console.debug must be in expression statement position",
        )),
        IRExpr::Conditional {
            test,
            cons,
            alt,
            cond_ty,
            span,
            ..
        } => {
            let ct = cond_ty.as_ref().ok_or_else(|| {
                diag(
                    f.cm.as_ref(),
                    &f.source_path,
                    *span,
                    "ternary condition type not filled by sem",
                )
            })?;
            let c = emit_expr(test, f, stmt_level)?;
            let cond_s = if is_numberish(ct) {
                format!("({c}) != 0")
            } else {
                format!("({c})")
            };
            let t = emit_expr(cons, f, stmt_level)?;
            let a = emit_expr(alt, f, stmt_level)?;
            Ok(format!("(if {cond_s} {{ {t} }} else {{ {a} }})"))
        }
        IRExpr::Seq { exprs, span } => emit_seq_expr(exprs, *span, f, stmt_level),
        IRExpr::Tpl { parts, .. } => emit_tpl(parts, f, stmt_level),
        IRExpr::Member {
            obj,
            prop,
            length_dispatch,
            ..
        } => {
            let o = emit_expr(obj, f, stmt_level)?;
            if prop == "length" {
                match length_dispatch {
                    Some(MemberLengthDispatch::JsStringUtf16) => {
                        Ok(format!("(({o}.encode_utf16().count()) as i32)"))
                    }
                    Some(MemberLengthDispatch::VecLen) => Ok(format!("({o}.len() as i32)")),
                    None => Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop)),
                }
            } else {
                Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop))
            }
        }
        IRExpr::OptionalMember {
            obj,
            prop,
            length_dispatch,
            ..
        } => match &**obj {
            IRExpr::Null(_) | IRExpr::Undefined(_) => Ok("()".to_string()),
            _ => {
                let o = emit_expr(obj, f, stmt_level)?;
                if prop == "length" {
                    match length_dispatch {
                        Some(MemberLengthDispatch::JsStringUtf16) => {
                            Ok(format!("(({o}.encode_utf16().count()) as i32)"))
                        }
                        Some(MemberLengthDispatch::VecLen) => Ok(format!("({o}.len() as i32)")),
                        None => Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop)),
                    }
                } else {
                    Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop))
                }
            }
        },
        IRExpr::MathBuiltin { kind, args, .. } => {
            use MathBuiltinKind::*;
            match kind {
                Abs => {
                    let a = emit_expr(&args[0], f, stmt_level)?;
                    Ok(format!("(({a}) as i32).abs()"))
                }
                Min => {
                    let a = emit_expr(&args[0], f, stmt_level)?;
                    let b = emit_expr(&args[1], f, stmt_level)?;
                    Ok(format!("(({a}) as i32).min(({b}) as i32)"))
                }
                Max => {
                    let a = emit_expr(&args[0], f, stmt_level)?;
                    let b = emit_expr(&args[1], f, stmt_level)?;
                    Ok(format!("(({a}) as i32).max(({b}) as i32)"))
                }
                Floor | Ceil => {
                    let n = emit_expr(&args[0], f, stmt_level)?;
                    Ok(format!("({n})"))
                }
            }
        }
        IRExpr::NullishCoalesce { left, right, .. } => {
            if matches!(&**left, IRExpr::Null(_) | IRExpr::Undefined(_)) {
                emit_expr(right, f, stmt_level)
            } else {
                emit_expr(left, f, stmt_level)
            }
        }
        IRExpr::ArrayLit { elems, .. } => {
            let mut xs = Vec::with_capacity(elems.len());
            for e in elems {
                xs.push(emit_expr(e, f, stmt_level)?);
            }
            Ok(format!("vec![{}]", xs.join(", ")))
        }
        IRExpr::ObjectLit { fields, .. } => {
            if fields.is_empty() {
                return Ok("std::collections::HashMap::new()".to_string());
            }
            let mut pairs = Vec::with_capacity(fields.len());
            for (k, v) in fields {
                pairs.push(format!(
                    "({:?}.to_string(), {})",
                    k,
                    emit_expr(v, f, stmt_level)?
                ));
            }
            Ok(format!(
                "std::collections::HashMap::from([{}])",
                pairs.join(", ")
            ))
        }
        IRExpr::Index { obj, index, .. } => {
            let o = emit_expr(obj, f, stmt_level)?;
            let i = emit_expr(index, f, stmt_level)?;
            Ok(format!("({o}[({i}) as usize])"))
        }
    }
}

fn emit_seq_expr(
    exprs: &[IRExpr],
    span: Span,
    f: &IRFunction,
    stmt_level: usize,
) -> Result<String, CompileError> {
    if exprs.is_empty() {
        return Err(diag(f.cm.as_ref(), &f.source_path, span, "empty sequence"));
    }
    if exprs.len() == 1 {
        return emit_expr(&exprs[0], f, stmt_level);
    }
    let inner = indent(stmt_level + 1);
    let close = indent(stmt_level);
    let mut block = String::new();
    block.push_str("({\n");
    for e in &exprs[..exprs.len() - 1] {
        block.push_str(&inner);
        block.push_str(&emit_expr_stmt(e, f, stmt_level)?);
        block.push_str(";\n");
    }
    block.push_str(&inner);
    block.push_str(&emit_expr(&exprs[exprs.len() - 1], f, stmt_level)?);
    block.push('\n');
    block.push_str(&close);
    block.push_str("})");
    Ok(block)
}

fn emit_tpl(parts: &[TplPart], f: &IRFunction, stmt_level: usize) -> Result<String, CompileError> {
    if parts.is_empty() {
        return Ok("\"\".to_string()".to_string());
    }
    if parts.len() == 1 {
        if let TplPart::Static(s) = &parts[0] {
            return Ok(format!("{:?}.to_string()", s));
        }
    }
    let mut fmt = String::new();
    let mut args: Vec<String> = Vec::new();
    for p in parts {
        match p {
            TplPart::Static(s) => {
                for ch in s.chars() {
                    match ch {
                        '{' => fmt.push_str("{{"),
                        '}' => fmt.push_str("}}"),
                        _ => fmt.push(ch),
                    }
                }
            }
            TplPart::Interp(e) => {
                fmt.push_str("{}");
                args.push(emit_expr(e, f, stmt_level)?);
            }
        }
    }
    let fmt_esc = fmt.replace('\\', "\\\\").replace('"', "\\\"");
    if args.is_empty() {
        return Ok(format!("format!(\"{fmt_esc}\")"));
    }
    Ok(format!("format!(\"{fmt_esc}\", {})", args.join(", ")))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::build::build_module;
    use crate::sem::check_module;
    use ts2rs_parser::parse_typescript_file;

    #[test]
    fn emit_rust_contains_ts_main_and_println() {
        let src = r#"function main(): number { return 42; }"#;
        let p = parse_typescript_file("t.ts", src).unwrap();
        let mut m = build_module(&p.program, &p.source_map, "t.ts").unwrap();
        check_module(&mut m).unwrap();
        let rs = emit_rust_with_options(&m, &CodegenOptions::default()).unwrap();
        assert!(rs.contains("fn ts_main"), "{rs}");
        assert!(rs.contains("println!"), "{rs}");
    }
}
