//! HIR → Rust 源码。

use crate::error::{diag, CompileError};
use crate::ir::*;
use swc_common::Span;

mod helpers;

/// 代码生成选项（默认不改变既有输出）。
#[derive(Debug, Clone, Default)]
pub struct CodegenOptions {
    /// 在每条语句前写入 `// ts: path:line:col`（与诊断格式一致）。
    pub span_comments: bool,
    /// 在语句（及顶层函数）前写入 TS 源码中的 leading 注释（`//` / `/* */` 转为 Rust 行注释）。
    pub emit_ts_source_comments: bool,
}

pub fn emit_rust(module: &IRModule) -> Result<String, CompileError> {
    emit_rust_with_options(module, &CodegenOptions::default())
}

pub fn emit_rust_with_options(
    module: &IRModule,
    opts: &CodegenOptions,
) -> Result<String, CompileError> {
    let mut out = String::new();
    out.push_str("// Generated by ts2rs — do not edit by hand.\n\n");

    if module_needs_http_stream(module) {
        out.push_str("use futures_util::StreamExt;\n\n#[derive(Clone)]\nstruct __Ts2rsStreamReadResult {\n    done: bool,\n    value: Vec<u8>,\n}\n\n");
    }

    if module_needs_fetch_text_helper(module) {
        out.push_str(
            "async fn __ts2rs_fetch_text(url: String) -> String {\n    reqwest::get(url.as_str())\n        .await\n        .expect(\"HTTP GET failed\")\n        .text()\n        .await\n        .expect(\"read response body failed\")\n}\n\n",
        );
    }
    if module_needs_fetch_request_helper(module) {
        out.push_str(
            r#"#[derive(Clone)]
struct __Ts2rsFetchInit {
    method: String,
    headers: Vec<(String, String)>,
    body: Option<String>,
}

async fn __ts2rs_fetch(url: String, init: Option<__Ts2rsFetchInit>) -> reqwest::Response {
    let client = reqwest::Client::new();
    let req = match init {
        None => client.get(url.as_str()),
        Some(i) => {
            let method = reqwest::Method::from_bytes(i.method.as_bytes())
                .expect("invalid HTTP method");
            let mut rb = client.request(method, url.as_str());
            for (k, v) in i.headers {
                rb = rb.header(k, v);
            }
            if let Some(b) = i.body {
                rb = rb.body(b);
            }
            rb
        }
    };
    req.send().await.expect("HTTP request failed")
}

"#,
        );
    }
    if module_needs_utf16_stdlib_helpers(module) {
        out.push_str(
            r#"fn __ts2rs_utf16_slice(s: &str, start: i32, end: Option<i32>, substring_swap: bool) -> String {
    let v: Vec<u16> = s.encode_utf16().collect();
    let nlen = v.len() as i32;
    let fix = |i: i32| -> i32 {
        if i < 0 {
            nlen + i
        } else {
            i
        }
    };
    let mut a = fix(start).clamp(0, nlen);
    let mut b = fix(end.unwrap_or(nlen)).clamp(0, nlen);
    if substring_swap && a > b {
        std::mem::swap(&mut a, &mut b);
    }
    if a > b {
        return String::new();
    }
    String::from_utf16_lossy(&v[a as usize..b as usize])
}

fn __ts2rs_utf16_index_of(haystack: &str, needle: &str, from_utf16: i32) -> f64 {
    let h: Vec<u16> = haystack.encode_utf16().collect();
    let n: Vec<u16> = needle.encode_utf16().collect();
    let hl = h.len() as i32;
    let nl = n.len() as i32;
    let mut start = from_utf16;
    if from_utf16 < 0 {
        start = hl + from_utf16;
    }
    if start < 0 {
        start = 0;
    }
    let usize_start = (start as usize).min(h.len());
    if n.is_empty() {
        return ((usize_start as i32).min(hl)) as f64;
    }
    if nl > hl || usize_start > h.len().saturating_sub(n.len()) {
        return -1_f64;
    }
    let last = h.len() - n.len();
    for i in usize_start..=last {
        if h[i..i + n.len()] == n[..] {
            return (i as i32) as f64;
        }
    }
    -1_f64
}

"#,
        );
    }
    if module_needs_json_stringify_helper(module) {
        out.push_str(
            r#"fn __ts2rs_json_escape_string(s: &str) -> String {
    let mut o = String::with_capacity(s.len() + 2);
    o.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => o.push_str("\\\\"),
            '"' => o.push_str("\\\""),
            '\n' => o.push_str("\\n"),
            '\r' => o.push_str("\\r"),
            '\t' => o.push_str("\\t"),
            c => o.push(c),
        }
    }
    o.push('"');
    o
}

"#,
        );
    }

    for c in &module.classes {
        let trait_name = format!("{}Dyn", c.name);
        let struct_name = format!("{}Obj", c.name);
        out.push_str(&format!("trait {trait_name} {{\n"));
        out.push_str("    fn __class_name(&self) -> &'static str;\n");
        out.push_str("}\n");
        out.push_str(&format!(
            "struct {struct_name} {{ data: std::collections::HashMap<String, f64> }}\n"
        ));
        out.push_str(&format!("impl {trait_name} for {struct_name} {{\n"));
        out.push_str("    fn __class_name(&self) -> &'static str {\n");
        // `Debug` escaping prevents `"` / `\n` in TS class names from breaking the generated literal.
        out.push_str(&format!("        {:?}\n", c.name));
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    let main_fn = module
        .fns
        .iter()
        .find(|f| f.name == "main")
        .expect("sem ensures main exists");

    for f in &module.fns {
        emit_fn(&mut out, f, 0, opts, module)?;
    }

    if main_fn.is_async {
        out.push_str("#[tokio::main]\nasync fn main() {\n");
    } else {
        out.push_str("fn main() {\n");
    }
    let ret_ty = rust_ty(&main_fn.ret, main_fn)?;
    let await_main = if main_fn.is_async { ".await" } else { "" };
    match ret_ty {
        "()" => {
            out.push_str(&format!("    ts_main(){await_main};\n"));
        }
        "f64" | "bool" | "String" => {
            out.push_str(&format!("    println!(\"{{}}\", ts_main(){await_main});\n"));
        }
        "Vec<f64>"
        | "Vec<String>"
        | "Vec<reqwest::Response>"
        | "std::collections::HashMap<String, f64>" => {
            out.push_str(&format!(
                "    println!(\"{{:?}}\", ts_main(){await_main});\n"
            ));
        }
        _ => {
            return Err(diag(
                main_fn.cm.as_ref(),
                &main_fn.source_path,
                main_fn.span,
                "unexpected return type classification in codegen",
            ));
        }
    }
    out.push_str("}\n");

    Ok(out)
}

fn module_needs_fetch_text_helper(module: &IRModule) -> bool {
    module
        .fns
        .iter()
        .any(|f| stmts_maybe_fetch_text_only(&f.body))
}

fn module_needs_fetch_request_helper(module: &IRModule) -> bool {
    module
        .fns
        .iter()
        .any(|f| stmts_maybe_fetch_request(&f.body))
}

fn module_needs_http_stream(module: &IRModule) -> bool {
    module.fns.iter().any(|f| stmts_maybe_http_stream(&f.body))
}

fn stmts_maybe_http_stream(stmts: &[IRStmt]) -> bool {
    stmts.iter().any(|s| match s {
        IRStmt::Let { init, .. } => init.as_ref().is_some_and(expr_maybe_http_stream),
        IRStmt::Assign { rhs, .. } => expr_maybe_http_stream(rhs),
        IRStmt::MemberAssign { rhs, .. } => expr_maybe_http_stream(rhs),
        IRStmt::Expr { expr, .. } => expr_maybe_http_stream(expr),
        IRStmt::Return { arg: Some(e), .. } => expr_maybe_http_stream(e),
        IRStmt::Return { arg: None, .. } => false,
        IRStmt::Block { stmts: b, .. } => stmts_maybe_http_stream(b),
        IRStmt::If {
            cond,
            then_b,
            else_b,
            ..
        } => {
            expr_maybe_http_stream(cond)
                || stmts_maybe_http_stream(then_b)
                || else_b.as_deref().is_some_and(stmts_maybe_http_stream)
        }
        IRStmt::While { cond, body, .. } => {
            expr_maybe_http_stream(cond) || stmts_maybe_http_stream(body)
        }
        IRStmt::ForIn { target, body, .. } => {
            expr_maybe_http_stream(target) || stmts_maybe_http_stream(body)
        }
        IRStmt::DoWhile { body, cond, .. } => {
            stmts_maybe_http_stream(body) || expr_maybe_http_stream(cond)
        }
        IRStmt::FnDecl { func, .. } => stmts_maybe_http_stream(&func.body),
        IRStmt::Empty { .. } | IRStmt::Break { .. } | IRStmt::Continue { .. } => false,
    })
}

fn expr_maybe_http_stream(e: &IRExpr) -> bool {
    match e {
        IRExpr::HttpResponseBodyGetReader { .. } | IRExpr::ReaderRead { .. } => true,
        IRExpr::Await { arg, .. } => expr_maybe_http_stream(arg),
        IRExpr::Binary { left, right, .. } => {
            expr_maybe_http_stream(left) || expr_maybe_http_stream(right)
        }
        IRExpr::Unary { arg, .. } => expr_maybe_http_stream(arg),
        IRExpr::Call { args, .. }
        | IRExpr::OptionalCall { args, .. }
        | IRExpr::BuiltinLog { args, .. }
        | IRExpr::MathBuiltin { args, .. }
        | IRExpr::NumberBuiltin { args, .. }
        | IRExpr::JsonBuiltin { args, .. }
        | IRExpr::UriBuiltin { args, .. } => args.iter().any(expr_maybe_http_stream),
        IRExpr::MethodCall { receiver, args, .. }
        | IRExpr::OptionalMethodCall { receiver, args, .. } => {
            expr_maybe_http_stream(receiver) || args.iter().any(expr_maybe_http_stream)
        }
        IRExpr::StringMethodBuiltin { receiver, args, .. } => {
            expr_maybe_http_stream(receiver) || args.iter().any(expr_maybe_http_stream)
        }
        IRExpr::Conditional {
            test, cons, alt, ..
        } => {
            expr_maybe_http_stream(test)
                || expr_maybe_http_stream(cons)
                || expr_maybe_http_stream(alt)
        }
        IRExpr::Seq { exprs, .. } => exprs.iter().any(expr_maybe_http_stream),
        IRExpr::Tpl { parts, .. } => parts.iter().any(|p| {
            if let TplPart::Interp(x) = p {
                expr_maybe_http_stream(x)
            } else {
                false
            }
        }),
        IRExpr::Member { obj, .. } | IRExpr::OptionalMember { obj, .. } => {
            expr_maybe_http_stream(obj)
        }
        IRExpr::NullishCoalesce { left, right, .. } => {
            expr_maybe_http_stream(left) || expr_maybe_http_stream(right)
        }
        IRExpr::ArrayLit { elems, .. } => elems.iter().any(expr_maybe_http_stream),
        IRExpr::ObjectLit { fields, .. } => fields.iter().any(|(_, v)| expr_maybe_http_stream(v)),
        IRExpr::Index { obj, index, .. } => {
            expr_maybe_http_stream(obj) || expr_maybe_http_stream(index)
        }
        IRExpr::ArrowFn { body, .. } => stmts_maybe_http_stream(body),
        IRExpr::PromiseAll { elems, .. } => elems.iter().any(expr_maybe_http_stream),
        IRExpr::Fetch { .. }
        | IRExpr::HttpResponseMethodBuiltin { .. }
        | IRExpr::Number(..)
        | IRExpr::Bool(..)
        | IRExpr::Str(..)
        | IRExpr::Ident(..)
        | IRExpr::Null(..)
        | IRExpr::Undefined(..)
        | IRExpr::This(..)
        | IRExpr::Super(..)
        | IRExpr::ReadStdinLine { .. }
        | IRExpr::FetchText { .. } => false,
    }
}

fn stmts_maybe_fetch_text_only(stmts: &[IRStmt]) -> bool {
    stmts.iter().any(stmt_maybe_fetch_text_only)
}

fn stmt_maybe_fetch_text_only(s: &IRStmt) -> bool {
    match s {
        IRStmt::Let { init, .. } => init.as_ref().is_some_and(expr_maybe_fetch_text_only),
        IRStmt::Assign { rhs, .. } | IRStmt::MemberAssign { rhs, .. } => {
            expr_maybe_fetch_text_only(rhs)
        }
        IRStmt::Expr { expr, .. } => expr_maybe_fetch_text_only(expr),
        IRStmt::Return { arg, .. } => arg.as_ref().is_some_and(expr_maybe_fetch_text_only),
        IRStmt::Block { stmts, .. } => stmts_maybe_fetch_text_only(stmts),
        IRStmt::If {
            cond,
            then_b,
            else_b,
            ..
        } => {
            expr_maybe_fetch_text_only(cond)
                || stmts_maybe_fetch_text_only(then_b)
                || else_b.as_deref().is_some_and(stmts_maybe_fetch_text_only)
        }
        IRStmt::While { cond, body, .. } => {
            expr_maybe_fetch_text_only(cond) || stmts_maybe_fetch_text_only(body)
        }
        IRStmt::ForIn { target, body, .. } => {
            expr_maybe_fetch_text_only(target) || stmts_maybe_fetch_text_only(body)
        }
        IRStmt::DoWhile { body, cond, .. } => {
            stmts_maybe_fetch_text_only(body) || expr_maybe_fetch_text_only(cond)
        }
        IRStmt::FnDecl { func, .. } => stmts_maybe_fetch_text_only(&func.body),
        _ => false,
    }
}

fn stmts_maybe_fetch_request(stmts: &[IRStmt]) -> bool {
    stmts.iter().any(stmt_maybe_fetch_request)
}

fn stmt_maybe_fetch_request(s: &IRStmt) -> bool {
    match s {
        IRStmt::Let { init, .. } => init.as_ref().is_some_and(expr_maybe_fetch_request),
        IRStmt::Assign { rhs, .. } | IRStmt::MemberAssign { rhs, .. } => {
            expr_maybe_fetch_request(rhs)
        }
        IRStmt::Expr { expr, .. } => expr_maybe_fetch_request(expr),
        IRStmt::Return { arg, .. } => arg.as_ref().is_some_and(expr_maybe_fetch_request),
        IRStmt::Block { stmts, .. } => stmts_maybe_fetch_request(stmts),
        IRStmt::If {
            cond,
            then_b,
            else_b,
            ..
        } => {
            expr_maybe_fetch_request(cond)
                || stmts_maybe_fetch_request(then_b)
                || else_b.as_deref().is_some_and(stmts_maybe_fetch_request)
        }
        IRStmt::While { cond, body, .. } => {
            expr_maybe_fetch_request(cond) || stmts_maybe_fetch_request(body)
        }
        IRStmt::ForIn { target, body, .. } => {
            expr_maybe_fetch_request(target) || stmts_maybe_fetch_request(body)
        }
        IRStmt::DoWhile { body, cond, .. } => {
            stmts_maybe_fetch_request(body) || expr_maybe_fetch_request(cond)
        }
        IRStmt::FnDecl { func, .. } => stmts_maybe_fetch_request(&func.body),
        _ => false,
    }
}

fn expr_maybe_fetch_text_only(e: &IRExpr) -> bool {
    match e {
        IRExpr::FetchText { .. } => true,
        IRExpr::Await { arg, .. } => expr_maybe_fetch_text_only(arg),
        IRExpr::Binary { left, right, .. } => {
            expr_maybe_fetch_text_only(left) || expr_maybe_fetch_text_only(right)
        }
        IRExpr::Unary { arg, .. } => expr_maybe_fetch_text_only(arg),
        IRExpr::Call { args, .. }
        | IRExpr::OptionalCall { args, .. }
        | IRExpr::BuiltinLog { args, .. }
        | IRExpr::MathBuiltin { args, .. }
        | IRExpr::NumberBuiltin { args, .. }
        | IRExpr::JsonBuiltin { args, .. }
        | IRExpr::UriBuiltin { args, .. } => args.iter().any(expr_maybe_fetch_text_only),
        IRExpr::MethodCall { receiver, args, .. }
        | IRExpr::OptionalMethodCall { receiver, args, .. } => {
            expr_maybe_fetch_text_only(receiver) || args.iter().any(expr_maybe_fetch_text_only)
        }
        IRExpr::StringMethodBuiltin { receiver, args, .. } => {
            expr_maybe_fetch_text_only(receiver) || args.iter().any(expr_maybe_fetch_text_only)
        }
        IRExpr::Conditional {
            test, cons, alt, ..
        } => {
            expr_maybe_fetch_text_only(test)
                || expr_maybe_fetch_text_only(cons)
                || expr_maybe_fetch_text_only(alt)
        }
        IRExpr::Seq { exprs, .. } => exprs.iter().any(expr_maybe_fetch_text_only),
        IRExpr::Tpl { parts, .. } => parts.iter().any(|p| {
            if let TplPart::Interp(x) = p {
                expr_maybe_fetch_text_only(x)
            } else {
                false
            }
        }),
        IRExpr::Member { obj, .. } | IRExpr::OptionalMember { obj, .. } => {
            expr_maybe_fetch_text_only(obj)
        }
        IRExpr::NullishCoalesce { left, right, .. } => {
            expr_maybe_fetch_text_only(left) || expr_maybe_fetch_text_only(right)
        }
        IRExpr::ArrayLit { elems, .. } => elems.iter().any(expr_maybe_fetch_text_only),
        IRExpr::ObjectLit { fields, .. } => {
            fields.iter().any(|(_, v)| expr_maybe_fetch_text_only(v))
        }
        IRExpr::Index { obj, index, .. } => {
            expr_maybe_fetch_text_only(obj) || expr_maybe_fetch_text_only(index)
        }
        IRExpr::ArrowFn { body, .. } => stmts_maybe_fetch_text_only(body),
        IRExpr::PromiseAll { elems, .. } => elems.iter().any(expr_maybe_fetch_text_only),
        IRExpr::HttpResponseBodyGetReader { response, .. } => expr_maybe_fetch_text_only(response),
        IRExpr::ReaderRead { .. } => false,
        IRExpr::Fetch { .. }
        | IRExpr::HttpResponseMethodBuiltin { .. }
        | IRExpr::Number(..)
        | IRExpr::Bool(..)
        | IRExpr::Str(..)
        | IRExpr::Ident(..)
        | IRExpr::Null(..)
        | IRExpr::Undefined(..)
        | IRExpr::This(..)
        | IRExpr::Super(..)
        | IRExpr::ReadStdinLine { .. } => false,
    }
}

fn expr_maybe_fetch_request(e: &IRExpr) -> bool {
    match e {
        IRExpr::Fetch { .. } => true,
        IRExpr::Await { arg, .. } => expr_maybe_fetch_request(arg),
        IRExpr::Binary { left, right, .. } => {
            expr_maybe_fetch_request(left) || expr_maybe_fetch_request(right)
        }
        IRExpr::Unary { arg, .. } => expr_maybe_fetch_request(arg),
        IRExpr::Call { args, .. }
        | IRExpr::OptionalCall { args, .. }
        | IRExpr::BuiltinLog { args, .. }
        | IRExpr::MathBuiltin { args, .. }
        | IRExpr::NumberBuiltin { args, .. }
        | IRExpr::JsonBuiltin { args, .. }
        | IRExpr::UriBuiltin { args, .. } => args.iter().any(expr_maybe_fetch_request),
        IRExpr::MethodCall { receiver, args, .. }
        | IRExpr::OptionalMethodCall { receiver, args, .. } => {
            expr_maybe_fetch_request(receiver) || args.iter().any(expr_maybe_fetch_request)
        }
        IRExpr::StringMethodBuiltin { receiver, args, .. } => {
            expr_maybe_fetch_request(receiver) || args.iter().any(expr_maybe_fetch_request)
        }
        IRExpr::HttpResponseMethodBuiltin { receiver, .. } => expr_maybe_fetch_request(receiver),
        IRExpr::Conditional {
            test, cons, alt, ..
        } => {
            expr_maybe_fetch_request(test)
                || expr_maybe_fetch_request(cons)
                || expr_maybe_fetch_request(alt)
        }
        IRExpr::Seq { exprs, .. } => exprs.iter().any(expr_maybe_fetch_request),
        IRExpr::Tpl { parts, .. } => parts.iter().any(|p| {
            if let TplPart::Interp(x) = p {
                expr_maybe_fetch_request(x)
            } else {
                false
            }
        }),
        IRExpr::Member { obj, .. } | IRExpr::OptionalMember { obj, .. } => {
            expr_maybe_fetch_request(obj)
        }
        IRExpr::NullishCoalesce { left, right, .. } => {
            expr_maybe_fetch_request(left) || expr_maybe_fetch_request(right)
        }
        IRExpr::ArrayLit { elems, .. } => elems.iter().any(expr_maybe_fetch_request),
        IRExpr::ObjectLit { fields, .. } => fields.iter().any(|(_, v)| expr_maybe_fetch_request(v)),
        IRExpr::Index { obj, index, .. } => {
            expr_maybe_fetch_request(obj) || expr_maybe_fetch_request(index)
        }
        IRExpr::ArrowFn { body, .. } => stmts_maybe_fetch_request(body),
        IRExpr::PromiseAll { elems, .. } => elems.iter().any(expr_maybe_fetch_request),
        IRExpr::HttpResponseBodyGetReader { response, .. } => expr_maybe_fetch_request(response),
        IRExpr::ReaderRead { .. } => false,
        IRExpr::FetchText { .. }
        | IRExpr::Number(..)
        | IRExpr::Bool(..)
        | IRExpr::Str(..)
        | IRExpr::Ident(..)
        | IRExpr::Null(..)
        | IRExpr::Undefined(..)
        | IRExpr::This(..)
        | IRExpr::Super(..)
        | IRExpr::ReadStdinLine { .. } => false,
    }
}

fn module_needs_json_stringify_helper(module: &IRModule) -> bool {
    module
        .fns
        .iter()
        .any(|f| stmts_maybe_json_stringify(&f.body))
}

fn stmts_maybe_json_stringify(stmts: &[IRStmt]) -> bool {
    stmts.iter().any(stmt_maybe_json_stringify)
}

fn stmt_maybe_json_stringify(s: &IRStmt) -> bool {
    match s {
        IRStmt::Let { init, .. } => init.as_ref().is_some_and(expr_maybe_json_stringify),
        IRStmt::Assign { rhs, .. } | IRStmt::MemberAssign { rhs, .. } => {
            expr_maybe_json_stringify(rhs)
        }
        IRStmt::Expr { expr, .. } => expr_maybe_json_stringify(expr),
        IRStmt::Return { arg, .. } => arg.as_ref().is_some_and(expr_maybe_json_stringify),
        IRStmt::Block { stmts, .. } => stmts_maybe_json_stringify(stmts),
        IRStmt::If {
            cond,
            then_b,
            else_b,
            ..
        } => {
            expr_maybe_json_stringify(cond)
                || stmts_maybe_json_stringify(then_b)
                || else_b.as_deref().is_some_and(stmts_maybe_json_stringify)
        }
        IRStmt::While { cond, body, .. } => {
            expr_maybe_json_stringify(cond) || stmts_maybe_json_stringify(body)
        }
        IRStmt::ForIn { target, body, .. } => {
            expr_maybe_json_stringify(target) || stmts_maybe_json_stringify(body)
        }
        IRStmt::DoWhile { body, cond, .. } => {
            stmts_maybe_json_stringify(body) || expr_maybe_json_stringify(cond)
        }
        IRStmt::FnDecl { func, .. } => stmts_maybe_json_stringify(&func.body),
        _ => false,
    }
}

fn module_needs_utf16_stdlib_helpers(module: &IRModule) -> bool {
    module.fns.iter().any(|f| stmts_maybe_utf16_stdlib(&f.body))
}

fn stmts_maybe_utf16_stdlib(stmts: &[IRStmt]) -> bool {
    stmts.iter().any(stmt_maybe_utf16_stdlib)
}

fn stmt_maybe_utf16_stdlib(s: &IRStmt) -> bool {
    match s {
        IRStmt::Let { init, .. } => init.as_ref().is_some_and(expr_maybe_utf16_stdlib),
        IRStmt::Assign { rhs, .. } | IRStmt::MemberAssign { rhs, .. } => {
            expr_maybe_utf16_stdlib(rhs)
        }
        IRStmt::Expr { expr, .. } => expr_maybe_utf16_stdlib(expr),
        IRStmt::Return { arg, .. } => arg.as_ref().is_some_and(expr_maybe_utf16_stdlib),
        IRStmt::Block { stmts, .. } => stmts_maybe_utf16_stdlib(stmts),
        IRStmt::If {
            cond,
            then_b,
            else_b,
            ..
        } => {
            expr_maybe_utf16_stdlib(cond)
                || stmts_maybe_utf16_stdlib(then_b)
                || else_b.as_deref().is_some_and(stmts_maybe_utf16_stdlib)
        }
        IRStmt::While { cond, body, .. } => {
            expr_maybe_utf16_stdlib(cond) || stmts_maybe_utf16_stdlib(body)
        }
        IRStmt::ForIn { target, body, .. } => {
            expr_maybe_utf16_stdlib(target) || stmts_maybe_utf16_stdlib(body)
        }
        IRStmt::DoWhile { body, cond, .. } => {
            stmts_maybe_utf16_stdlib(body) || expr_maybe_utf16_stdlib(cond)
        }
        IRStmt::FnDecl { func, .. } => stmts_maybe_utf16_stdlib(&func.body),
        _ => false,
    }
}

fn expr_maybe_utf16_stdlib(e: &IRExpr) -> bool {
    match e {
        IRExpr::StringMethodBuiltin { .. } => true,
        IRExpr::Binary { left, right, .. } => {
            expr_maybe_utf16_stdlib(left) || expr_maybe_utf16_stdlib(right)
        }
        IRExpr::Unary { arg, .. } => expr_maybe_utf16_stdlib(arg),
        IRExpr::Call { args, .. }
        | IRExpr::OptionalCall { args, .. }
        | IRExpr::MethodCall { args, .. }
        | IRExpr::OptionalMethodCall { args, .. }
        | IRExpr::BuiltinLog { args, .. }
        | IRExpr::MathBuiltin { args, .. }
        | IRExpr::NumberBuiltin { args, .. }
        | IRExpr::JsonBuiltin { args, .. }
        | IRExpr::UriBuiltin { args, .. } => args.iter().any(expr_maybe_utf16_stdlib),
        IRExpr::Conditional {
            test, cons, alt, ..
        } => {
            expr_maybe_utf16_stdlib(test)
                || expr_maybe_utf16_stdlib(cons)
                || expr_maybe_utf16_stdlib(alt)
        }
        IRExpr::Seq { exprs, .. } => exprs.iter().any(expr_maybe_utf16_stdlib),
        IRExpr::Tpl { parts, .. } => parts.iter().any(|p| match p {
            TplPart::Interp(x) => expr_maybe_utf16_stdlib(x),
            TplPart::Static(_) => false,
        }),
        IRExpr::Member { obj, .. } | IRExpr::OptionalMember { obj, .. } => {
            expr_maybe_utf16_stdlib(obj)
        }
        IRExpr::NullishCoalesce { left, right, .. } => {
            expr_maybe_utf16_stdlib(left) || expr_maybe_utf16_stdlib(right)
        }
        IRExpr::ArrayLit { elems, .. } => elems.iter().any(expr_maybe_utf16_stdlib),
        IRExpr::ObjectLit { fields, .. } => fields.iter().any(|(_, v)| expr_maybe_utf16_stdlib(v)),
        IRExpr::Index { obj, index, .. } => {
            expr_maybe_utf16_stdlib(obj) || expr_maybe_utf16_stdlib(index)
        }
        IRExpr::ArrowFn { body, .. } => stmts_maybe_utf16_stdlib(body),
        IRExpr::Await { arg, .. } => expr_maybe_utf16_stdlib(arg),
        IRExpr::FetchText { url, .. } => expr_maybe_utf16_stdlib(url),
        IRExpr::Fetch { url, init, .. } => {
            expr_maybe_utf16_stdlib(url)
                || init
                    .as_ref()
                    .is_some_and(|i| i.body.as_ref().is_some_and(|b| expr_maybe_utf16_stdlib(b)))
        }
        IRExpr::HttpResponseMethodBuiltin { receiver, .. } => expr_maybe_utf16_stdlib(receiver),
        IRExpr::PromiseAll { elems, .. } => elems.iter().any(expr_maybe_utf16_stdlib),
        _ => false,
    }
}

fn expr_maybe_json_stringify(e: &IRExpr) -> bool {
    match e {
        IRExpr::JsonBuiltin {
            kind: JsonBuiltinKind::Stringify,
            ..
        } => true,
        IRExpr::Binary { left, right, .. } => {
            expr_maybe_json_stringify(left) || expr_maybe_json_stringify(right)
        }
        IRExpr::Unary { arg, .. } => expr_maybe_json_stringify(arg),
        IRExpr::Call { args, .. }
        | IRExpr::OptionalCall { args, .. }
        | IRExpr::MethodCall { args, .. }
        | IRExpr::OptionalMethodCall { args, .. }
        | IRExpr::BuiltinLog { args, .. }
        | IRExpr::MathBuiltin { args, .. }
        | IRExpr::NumberBuiltin { args, .. }
        | IRExpr::JsonBuiltin { args, .. }
        | IRExpr::UriBuiltin { args, .. } => args.iter().any(expr_maybe_json_stringify),
        IRExpr::StringMethodBuiltin { receiver, args, .. } => {
            expr_maybe_json_stringify(receiver) || args.iter().any(expr_maybe_json_stringify)
        }
        IRExpr::Conditional {
            test, cons, alt, ..
        } => {
            expr_maybe_json_stringify(test)
                || expr_maybe_json_stringify(cons)
                || expr_maybe_json_stringify(alt)
        }
        IRExpr::Seq { exprs, .. } => exprs.iter().any(expr_maybe_json_stringify),
        IRExpr::Tpl { parts, .. } => parts.iter().any(|p| match p {
            TplPart::Interp(x) => expr_maybe_json_stringify(x),
            TplPart::Static(_) => false,
        }),
        IRExpr::Member { obj, .. } | IRExpr::OptionalMember { obj, .. } => {
            expr_maybe_json_stringify(obj)
        }
        IRExpr::NullishCoalesce { left, right, .. } => {
            expr_maybe_json_stringify(left) || expr_maybe_json_stringify(right)
        }
        IRExpr::ArrayLit { elems, .. } => elems.iter().any(expr_maybe_json_stringify),
        IRExpr::ObjectLit { fields, .. } => {
            fields.iter().any(|(_, v)| expr_maybe_json_stringify(v))
        }
        IRExpr::Index { obj, index, .. } => {
            expr_maybe_json_stringify(obj) || expr_maybe_json_stringify(index)
        }
        IRExpr::ArrowFn { body, .. } => stmts_maybe_json_stringify(body),
        IRExpr::Await { arg, .. } => expr_maybe_json_stringify(arg),
        IRExpr::FetchText { url, .. } => expr_maybe_json_stringify(url),
        IRExpr::Fetch { url, init, .. } => {
            expr_maybe_json_stringify(url)
                || init.as_ref().is_some_and(|i| {
                    i.body
                        .as_ref()
                        .is_some_and(|b| expr_maybe_json_stringify(b))
                })
        }
        IRExpr::HttpResponseMethodBuiltin { receiver, .. } => expr_maybe_json_stringify(receiver),
        IRExpr::PromiseAll { elems, .. } => elems.iter().any(expr_maybe_json_stringify),
        _ => false,
    }
}

fn rust_fn_name(name: &str) -> &str {
    helpers::rust_fn_name(name)
}

fn is_numberish(t: &TsType) -> bool {
    helpers::is_numberish(t)
}

fn is_booleanish(t: &TsType) -> bool {
    helpers::is_booleanish(t)
}

fn is_stringish(t: &TsType) -> bool {
    helpers::is_stringish(t)
}

fn rust_ty(t: &TsType, f: &IRFunction) -> Result<&'static str, CompileError> {
    helpers::rust_ty(t, f)
}

fn emit_fn(
    out: &mut String,
    f: &IRFunction,
    level: usize,
    opts: &CodegenOptions,
    module: &IRModule,
) -> Result<(), CompileError> {
    if !f.type_params.is_empty() {
        return Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            f.span,
            format!(
                "internal error: generic function `{}` must be monomorphized before codegen",
                f.name
            ),
        ));
    }
    let ind = indent(level);
    emit_frozen_ts_leading_comments(out, &ind, module, &f.source_path, f.span, opts);
    let name = rust_fn_name(&f.name);
    out.push_str(&ind);
    if f.is_async {
        out.push_str("async ");
    }
    out.push_str("fn ");
    out.push_str(name);
    out.push('(');
    for (i, (p, ty)) in f.params.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(p);
        out.push_str(": ");
        out.push_str(rust_ty(ty, f)?);
    }
    out.push_str(") -> ");
    out.push_str(rust_ty(&f.ret, f)?);
    out.push_str(" {\n");
    for s in &f.body {
        emit_stmt(out, s, level + 1, f, opts, module)?;
    }
    out.push_str(&ind);
    out.push_str("}\n");
    if level == 0 {
        out.push('\n');
    }
    Ok(())
}

fn indent(n: usize) -> String {
    helpers::indent(n)
}

fn stmt_span(s: &IRStmt) -> Span {
    helpers::stmt_span(s)
}

fn emit_ts_span_comment(out: &mut String, ind: &str, f: &IRFunction, span: Span) {
    helpers::emit_ts_span_comment(out, ind, f, span);
}

fn emit_frozen_ts_leading_comments(
    out: &mut String,
    ind: &str,
    module: &IRModule,
    source_path: &str,
    span: Span,
    opts: &CodegenOptions,
) {
    if !opts.emit_ts_source_comments {
        return;
    }
    let Some(map) = module.ts_comments_by_path.get(source_path) else {
        return;
    };
    let Some(lines) = map.get(&span.lo().0) else {
        return;
    };
    for line in lines {
        out.push_str(ind);
        out.push_str("// ");
        out.push_str(line);
        out.push('\n');
    }
}

fn emit_stmt(
    out: &mut String,
    s: &IRStmt,
    level: usize,
    f: &IRFunction,
    opts: &CodegenOptions,
    module: &IRModule,
) -> Result<(), CompileError> {
    let ind = indent(level);
    let sp = stmt_span(s);
    emit_frozen_ts_leading_comments(out, &ind, module, &f.source_path, sp, opts);
    if opts.span_comments && !matches!(s, IRStmt::Empty { .. }) {
        emit_ts_span_comment(out, &ind, f, sp);
    }
    match s {
        IRStmt::Empty { .. } => {}
        IRStmt::Let {
            name,
            ty,
            init,
            mutable,
            ..
        } => {
            if *ty == TsType::ReadableStreamDefaultReader {
                if let Some(IRExpr::HttpResponseBodyGetReader {
                    response,
                    stream_slot: Some(slot),
                    ..
                }) = init.as_ref()
                {
                    out.push_str(&ind);
                    out.push_str(&format!("let mut __ts2rs_stream_{slot} = "));
                    out.push_str(&emit_expr(response, f, level, module)?);
                    out.push_str(".bytes_stream();\n");
                    return Ok(());
                }
                return Err(diag(
                    f.cm.as_ref(),
                    &f.source_path,
                    stmt_span(s),
                    "internal error: `ReadableStreamDefaultReader` binding must use `response.body.getReader()` with a stream slot",
                ));
            }
            out.push_str(&ind);
            if *mutable {
                out.push_str("let mut ");
            } else {
                out.push_str("let ");
            }
            out.push_str(name);
            out.push_str(": ");
            out.push_str(rust_ty(ty, f)?);
            if let Some(init_e) = init {
                out.push_str(" = ");
                out.push_str(&emit_expr(init_e, f, level, module)?);
            }
            out.push_str(";\n");
        }
        IRStmt::Assign { name, rhs, .. } => {
            out.push_str(&ind);
            out.push_str(name);
            out.push_str(" = ");
            out.push_str(&emit_expr(rhs, f, level, module)?);
            out.push_str(";\n");
        }
        IRStmt::MemberAssign { obj, prop, rhs, .. } => {
            out.push_str(&ind);
            out.push_str(obj);
            out.push_str(".insert(");
            out.push_str(&format!("{prop:?}.to_string(), "));
            out.push_str(&emit_expr(rhs, f, level, module)?);
            out.push_str(");\n");
        }
        IRStmt::Expr { expr, .. } => {
            out.push_str(&ind);
            out.push_str(&emit_expr_stmt(expr, f, level, module)?);
            out.push_str(";\n");
        }
        IRStmt::Return { arg, .. } => {
            out.push_str(&ind);
            out.push_str("return ");
            if let Some(e) = arg {
                out.push_str(&emit_expr(e, f, level, module)?);
            }
            out.push_str(";\n");
        }
        IRStmt::Block { stmts, .. } => {
            out.push_str(&ind);
            out.push_str("{\n");
            for x in stmts {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::If {
            cond,
            cond_ty,
            then_b,
            else_b,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("if ");
            let c = emit_expr(cond, f, level, module)?;
            if is_numberish(cond_ty) {
                out.push_str(&format!("({c}) != 0.0"));
            } else {
                out.push_str(&format!("({c})"));
            }
            out.push_str(" {\n");
            for x in then_b {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push('}');
            if let Some(else_b) = else_b {
                out.push_str(" else {\n");
                for x in else_b {
                    emit_stmt(out, x, level + 1, f, opts, module)?;
                }
                out.push_str(&ind);
                out.push_str("}\n");
            } else {
                out.push('\n');
            }
        }
        IRStmt::While {
            cond,
            cond_ty,
            body,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("while ");
            let c = emit_expr(cond, f, level, module)?;
            if is_numberish(cond_ty) {
                out.push_str(&format!("({c}) != 0.0"));
            } else {
                out.push_str(&format!("({c})"));
            }
            out.push_str(" {\n");
            for x in body {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::ForIn {
            key,
            key_ty,
            target,
            kind,
            body,
            span,
        } => {
            let t = emit_expr(target, f, level, module)?;
            let key_rust_ty = rust_ty(key_ty, f)?;
            let tmp = format!("__forin_target_{}", span.lo.0);
            out.push_str(&ind);
            out.push_str(&format!("let {tmp} = {t};\n"));
            match kind {
                Some(ForInKind::ObjectKeys) => {
                    out.push_str(&ind);
                    out.push_str(&format!("for __k in {tmp}.keys() {{\n"));
                    out.push_str(&indent(level + 1));
                    out.push_str(&format!("let {key}: {key_rust_ty} = __k.clone();\n"));
                }
                Some(ForInKind::ArrayIndices) => {
                    out.push_str(&ind);
                    out.push_str(&format!("for __i in 0..{tmp}.len() {{\n"));
                    out.push_str(&indent(level + 1));
                    out.push_str(&format!("let {key}: {key_rust_ty} = __i.to_string();\n"));
                }
                None => {
                    return Err(diag(
                        f.cm.as_ref(),
                        &f.source_path,
                        *span,
                        "for..in kind missing from sem",
                    ));
                }
            }
            for x in body {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::DoWhile {
            body,
            cond,
            cond_ty,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("loop {\n");
            for x in body {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            let c = emit_expr(cond, f, level, module)?;
            out.push_str(&indent(level + 1));
            if is_numberish(cond_ty) {
                out.push_str(&format!("if ({c}) == 0 {{ break; }}\n"));
            } else {
                out.push_str(&format!("if !({c}) {{ break; }}\n"));
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::Break { .. } => {
            out.push_str(&ind);
            out.push_str("break;\n");
        }
        IRStmt::Continue { .. } => {
            out.push_str(&ind);
            out.push_str("continue;\n");
        }
        IRStmt::FnDecl { func, .. } => {
            emit_fn(out, func, level, opts, module)?;
        }
    }
    Ok(())
}

fn emit_expr_stmt(
    e: &IRExpr,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    match e {
        IRExpr::BuiltinLog { args, stderr, .. } => {
            emit_builtin_log(args, f, stmt_level, *stderr, module)
        }
        _ => emit_expr(e, f, stmt_level, module),
    }
}

/// `println!`/`eprintln!` format strings are built only from fixed `"{}"` segments; user text is never interpolated into the format template.
fn emit_builtin_log(
    args: &[IRExpr],
    f: &IRFunction,
    stmt_level: usize,
    to_stderr: bool,
    module: &IRModule,
) -> Result<String, CompileError> {
    let mac = if to_stderr { "eprintln!" } else { "println!" };
    if args.is_empty() {
        return Ok(format!("{mac}()"));
    }
    let mut parts = Vec::new();
    for a in args {
        parts.push(emit_expr(a, f, stmt_level, module)?);
    }
    if parts.len() == 1 {
        return Ok(format!("{mac}(\"{{}}\", {})", parts[0]));
    }
    let fmt_str = std::iter::repeat("{}")
        .take(parts.len())
        .collect::<Vec<_>>()
        .join(" ");
    let joined = parts.join(", ");
    Ok(format!("{mac}(\"{fmt_str}\", {joined})"))
}

fn emit_expr(
    e: &IRExpr,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    match e {
        IRExpr::Number(n, _) => Ok(helpers::rust_f64_literal(*n)),
        IRExpr::Bool(b, _) => Ok(format!("{b}")),
        IRExpr::Str(s, _) => Ok(format!("{:?}.to_string()", s)),
        IRExpr::Null(_) | IRExpr::Undefined(_) => Ok("()".to_string()),
        IRExpr::This(_) => Ok("__self".to_string()),
        IRExpr::Super(_) => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            f.span,
            "`super` expression cannot be emitted directly",
        )),
        IRExpr::Ident(name, _) => Ok(name.clone()),
        IRExpr::Unary { op, arg, .. } => {
            let a = emit_expr(arg, f, stmt_level, module)?;
            match op {
                IRUnaryOp::Neg => Ok(format!("(-({a}))")),
                IRUnaryOp::Not => Ok(format!("!({a})")),
            }
        }
        IRExpr::Binary {
            op,
            left,
            right,
            kind,
            span,
        } => {
            let l = emit_expr(left, f, stmt_level, module)?;
            let r = emit_expr(right, f, stmt_level, module)?;
            use IRBinOp::*;
            let mid = match op {
                Add => {
                    if matches!(kind, Some(BinaryKind::StrConcat)) {
                        format!("format!(\"{{}}{{}}\", {l}, {r})")
                    } else {
                        format!("({l} + {r})")
                    }
                }
                Sub => format!("({l} - {r})"),
                Mul => format!("({l} * {r})"),
                Div => format!("({l} / {r})"),
                Eq => format!("({l} == {r})"),
                Ne => format!("({l} != {r})"),
                Lt => format!("({l} < {r})"),
                Le => format!("({l} <= {r})"),
                Gt => format!("({l} > {r})"),
                Ge => format!("({l} >= {r})"),
                LogicalAnd | LogicalOr => {
                    let (lhs_n, rhs_n) = match kind {
                        Some(BinaryKind::Logical {
                            lhs_number_truthy,
                            rhs_number_truthy,
                        }) => (*lhs_number_truthy, *rhs_number_truthy),
                        _ => {
                            return Err(diag(
                                f.cm.as_ref(),
                                &f.source_path,
                                *span,
                                "`&&` / `||` missing Logical kind (semantic pass bug)",
                            ));
                        }
                    };
                    let ls = if lhs_n { format!("({l} != 0.0)") } else { l };
                    let rs = if rhs_n { format!("({r} != 0.0)") } else { r };
                    match op {
                        LogicalAnd => format!("({ls} && {rs})"),
                        LogicalOr => format!("({ls} || {rs})"),
                        _ => unreachable!(),
                    }
                }
            };
            Ok(mid)
        }
        IRExpr::Call { callee, args, .. } | IRExpr::OptionalCall { callee, args, .. } => {
            let name = rust_fn_name(callee);
            let mut a = Vec::new();
            for x in args {
                a.push(emit_expr(x, f, stmt_level, module)?);
            }
            Ok(format!("{}({})", name, a.join(", ")))
        }
        IRExpr::ArrowFn {
            params, ret, body, ..
        } => {
            if params.len() != 1 || !is_numberish(&params[0].1) || !is_numberish(ret) {
                return Err(diag(
                    f.cm.as_ref(),
                    &f.source_path,
                    f.span,
                    "current closure codegen supports only `(number) => number`",
                ));
            }
            let (pname, pty) = &params[0];
            let mut body_out = String::new();
            for s in body {
                emit_stmt(
                    &mut body_out,
                    s,
                    stmt_level + 1,
                    f,
                    &CodegenOptions::default(),
                    module,
                )?;
            }
            Ok(format!(
                "std::rc::Rc::new(move |{}: {}| -> {} {{\n{}{} }})",
                pname,
                rust_ty(pty, f)?,
                rust_ty(ret, f)?,
                body_out,
                indent(stmt_level)
            ))
        }
        IRExpr::MethodCall {
            receiver,
            method,
            args,
            ..
        }
        | IRExpr::OptionalMethodCall {
            receiver,
            method,
            args,
            ..
        } => {
            let name = rust_fn_name(method);
            let mut a = vec![emit_expr(receiver, f, stmt_level, module)?];
            for x in args {
                a.push(emit_expr(x, f, stmt_level, module)?);
            }
            Ok(format!("{}({})", name, a.join(", ")))
        }
        IRExpr::BuiltinLog { span, .. } => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            *span,
            "console.log / console.error / console.debug must be in expression statement position",
        )),
        IRExpr::Conditional {
            test,
            cons,
            alt,
            cond_ty,
            span,
            ..
        } => {
            let ct = cond_ty.as_ref().ok_or_else(|| {
                diag(
                    f.cm.as_ref(),
                    &f.source_path,
                    *span,
                    "ternary condition type not filled by sem",
                )
            })?;
            let c = emit_expr(test, f, stmt_level, module)?;
            let cond_s = if is_numberish(ct) {
                format!("({c}) != 0.0")
            } else {
                format!("({c})")
            };
            let t = emit_expr(cons, f, stmt_level, module)?;
            let a = emit_expr(alt, f, stmt_level, module)?;
            Ok(format!("(if {cond_s} {{ {t} }} else {{ {a} }})"))
        }
        IRExpr::Seq { exprs, span } => emit_seq_expr(exprs, *span, f, stmt_level, module),
        IRExpr::Tpl { parts, .. } => emit_tpl(parts, f, stmt_level, module),
        IRExpr::Member {
            obj,
            prop,
            span: member_span,
            length_dispatch,
            http_response_member,
            stream_read_member,
            ..
        } => {
            let o = emit_expr(obj, f, stmt_level, module)?;
            if let Some(h) = http_response_member {
                return match h {
                    HttpResponseMember::Status => {
                        Ok(format!("(({o}).status().as_u16() as f64)"))
                    }
                    HttpResponseMember::Ok => Ok(format!("(({o}).status().is_success())")),
                    HttpResponseMember::Body => Err(diag(
                        f.cm.as_ref(),
                        &f.source_path,
                        *member_span,
                        "use `response.body.getReader()` — `response.body` cannot be read as a value alone",
                    )),
                };
            }
            if let Some(sr) = stream_read_member {
                return match sr {
                    StreamReadResultMember::Done => Ok(format!("(({o}).done)")),
                    StreamReadResultMember::Value => Ok(format!("(({o}).value)")),
                };
            }
            if prop == "length" {
                match length_dispatch {
                    Some(MemberLengthDispatch::JsStringUtf16) => {
                        Ok(format!("(({o}.encode_utf16().count() as f64))"))
                    }
                    Some(MemberLengthDispatch::VecLen) => Ok(format!("({o}.len() as f64)")),
                    Some(MemberLengthDispatch::Uint8ArrayLen) => {
                        Ok(format!("({o}.len() as f64)"))
                    }
                    None => Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop)),
                }
            } else {
                Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop))
            }
        }
        IRExpr::OptionalMember {
            obj,
            prop,
            span: om_span,
            length_dispatch,
            http_response_member,
            stream_read_member,
            ..
        } => match &**obj {
            IRExpr::Null(_) | IRExpr::Undefined(_) => Ok("()".to_string()),
            _ => {
                let o = emit_expr(obj, f, stmt_level, module)?;
                if let Some(h) = http_response_member {
                    return match h {
                        HttpResponseMember::Status => {
                            Ok(format!("(({o}).status().as_u16() as f64)"))
                        }
                        HttpResponseMember::Ok => Ok(format!("(({o}).status().is_success())")),
                        HttpResponseMember::Body => Err(diag(
                            f.cm.as_ref(),
                            &f.source_path,
                            *om_span,
                            "use `response.body.getReader()` — `response.body` cannot be read as a value alone",
                        )),
                    };
                }
                if let Some(sr) = stream_read_member {
                    return match sr {
                        StreamReadResultMember::Done => Ok(format!("(({o}).done)")),
                        StreamReadResultMember::Value => Ok(format!("(({o}).value)")),
                    };
                }
                if prop == "length" {
                    match length_dispatch {
                        Some(MemberLengthDispatch::JsStringUtf16) => {
                            Ok(format!("(({o}.encode_utf16().count() as f64))"))
                        }
                        Some(MemberLengthDispatch::VecLen) => Ok(format!("({o}.len() as f64)")),
                        Some(MemberLengthDispatch::Uint8ArrayLen) => {
                            Ok(format!("({o}.len() as f64)"))
                        }
                        None => Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop)),
                    }
                } else {
                    Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop))
                }
            }
        },
        IRExpr::MathBuiltin { kind, args, .. } => {
            use MathBuiltinKind::*;
            match kind {
                Abs => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("(({a}).abs())"))
                }
                Min => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    let b = emit_expr(&args[1], f, stmt_level, module)?;
                    Ok(format!("(({a}).min({b}))"))
                }
                Max => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    let b = emit_expr(&args[1], f, stmt_level, module)?;
                    Ok(format!("(({a}).max({b}))"))
                }
                Floor => {
                    let n = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("(({n}).floor())"))
                }
                Ceil => {
                    let n = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("(({n}).ceil())"))
                }
                Trunc => {
                    let n = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("(({n}).trunc())"))
                }
                Round => {
                    let n = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("(({n}).round())"))
                }
                Sign => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("(({a}).signum())"))
                }
                Pow => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    let b = emit_expr(&args[1], f, stmt_level, module)?;
                    Ok(format!(
                        "({{ let __b = {b}; if __b < 0.0 {{ panic!(\"Math.pow: negative exponent\"); }} ({a}).powf(__b) }})"
                    ))
                }
            }
        }
        IRExpr::NumberBuiltin { kind, args, .. } => {
            use NumberBuiltinKind::*;
            match kind {
                ParseInt => {
                    let s = emit_expr(&args[0], f, stmt_level, module)?;
                    if args.len() == 1 {
                        Ok(format!(
                            "({{ let __p = ({s}).trim().parse::<i64>().unwrap_or(0); __p as f64 }})"
                        ))
                    } else {
                        let radix = emit_expr(&args[1], f, stmt_level, module)?;
                        Ok(format!(
                            "({{ let __r = ({radix}) as u32; i64::from_str_radix(({s}).trim(), __r).unwrap_or(0) as f64 }})"
                        ))
                    }
                }
                ParseFloat => {
                    let s = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("(({s}).trim().parse::<f64>().unwrap_or(0.0))"))
                }
            }
        }
        IRExpr::JsonBuiltin {
            kind,
            args,
            span,
            stringify_inferred_ty,
        } => match kind {
            JsonBuiltinKind::Stringify => {
                let inner = emit_expr(&args[0], f, stmt_level, module)?;
                let ty = stringify_inferred_ty.as_ref().ok_or_else(|| {
                    diag(
                        f.cm.as_ref(),
                        &f.source_path,
                        *span,
                        "JSON.stringify: missing inferred type (sem bug)",
                    )
                })?;
                if is_stringish(ty) {
                    Ok(format!("__ts2rs_json_escape_string(&({inner}))"))
                } else if is_numberish(ty) || is_booleanish(ty) {
                    Ok(format!("format!(\"{{}}\", {inner})"))
                } else {
                    Err(diag(
                        f.cm.as_ref(),
                        &f.source_path,
                        *span,
                        "JSON.stringify: unsupported type for codegen",
                    ))
                }
            }
            JsonBuiltinKind::Parse => {
                let s = emit_expr(&args[0], f, stmt_level, module)?;
                Ok(format!(
                    "serde_json::from_str::<f64>(({s}).trim()).expect(\"JSON.parse: expected JSON number\")"
                ))
            }
        },
        IRExpr::UriBuiltin { kind, args, .. } => {
            let s = emit_expr(&args[0], f, stmt_level, module)?;
            match kind {
                UriBuiltinKind::EncodeComponent => Ok(format!(
                    "urlencoding::encode(&({s})).into_owned()"
                )),
                UriBuiltinKind::DecodeComponent => Ok(format!(
                    "urlencoding::decode(&({s})).expect(\"decodeURIComponent: invalid percent-encoding\").into_owned()"
                )),
            }
        },
        IRExpr::StringMethodBuiltin {
            kind,
            receiver,
            args,
            span,
        } => emit_string_method_builtin(kind, receiver, args, *span, f, stmt_level, module),
        IRExpr::ReadStdinLine { .. } => Ok(r#"({
    use std::io::BufRead;
    let mut __line = String::new();
    let _ = std::io::stdin().lock().read_line(&mut __line);
    if __line.ends_with('\n') {
        __line.pop();
        if __line.ends_with('\r') {
            __line.pop();
        }
    }
    __line
})"#
        .to_string()),
        IRExpr::NullishCoalesce { left, right, .. } => {
            if matches!(&**left, IRExpr::Null(_) | IRExpr::Undefined(_)) {
                emit_expr(right, f, stmt_level, module)
            } else {
                emit_expr(left, f, stmt_level, module)
            }
        }
        IRExpr::ArrayLit { elems, .. } => {
            let mut xs = Vec::with_capacity(elems.len());
            for e in elems {
                xs.push(emit_expr(e, f, stmt_level, module)?);
            }
            Ok(format!("vec![{}]", xs.join(", ")))
        }
        IRExpr::ObjectLit { fields, .. } => {
            if fields.is_empty() {
                return Ok("std::collections::HashMap::new()".to_string());
            }
            let mut pairs = Vec::with_capacity(fields.len());
            for (k, v) in fields {
                pairs.push(format!(
                    "({:?}.to_string(), {})",
                    k,
                    emit_expr(v, f, stmt_level, module)?
                ));
            }
            Ok(format!(
                "std::collections::HashMap::from([{}])",
                pairs.join(", ")
            ))
        }
        IRExpr::Index {
            obj,
            index,
            index_kind,
            ..
        } => {
            let o = emit_expr(obj, f, stmt_level, module)?;
            let i = emit_expr(index, f, stmt_level, module)?;
            match index_kind {
                Some(IndexKind::StringUtf16) => Ok(format!(
                    "({{ let __s = &({o}); let __ii = ({i}) as i32; let __v: Vec<u16> = __s.encode_utf16().collect(); let __len = __v.len() as i32; let __j = if __ii < 0 {{ __len + __ii }} else {{ __ii }}; if __j < 0 || __j >= __len {{ String::new() }} else {{ String::from_utf16_lossy(&[__v[__j as usize]]) }} }})"
                )),
                Some(IndexKind::ArrayStringElem) => {
                    Ok(format!("({o}[({i}) as usize]).clone()"))
                }
                _ => Ok(format!("({o}[({i}) as usize])")),
            }
        }
        IRExpr::FetchText { url, .. } => {
            let u = emit_expr(url, f, stmt_level, module)?;
            Ok(format!("__ts2rs_fetch_text({u})"))
        }
        IRExpr::Fetch { url, init, .. } => emit_fetch_call(url, init, f, stmt_level, module),
        IRExpr::HttpResponseMethodBuiltin { span, .. } => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            *span,
            "use `await response.text()`, `await response.json()`, or `await reader.read()` on the promise from `fetch` / stream reader",
        )),
        IRExpr::HttpResponseBodyGetReader { span, .. } => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            *span,
            "use `let reader = response.body.getReader()` then `await reader.read()` in a loop",
        )),
        IRExpr::ReaderRead { span, .. } => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            *span,
            "use `await reader.read()` (must be under `await`)",
        )),
        IRExpr::PromiseAll { elems, .. } => {
            let mut parts = Vec::with_capacity(elems.len());
            for e in elems {
                let s = emit_expr(e, f, stmt_level, module)?;
                parts.push(format!("({s}).await"));
            }
            Ok(format!("vec![{}]", parts.join(", ")))
        }
        IRExpr::Await { arg, .. } => match &**arg {
            IRExpr::HttpResponseMethodBuiltin {
                kind,
                receiver,
                ..
            } => {
                let r = emit_expr(receiver, f, stmt_level, module)?;
                match kind {
                    HttpResponseMethodKind::Text => Ok(format!(
                        "({r}).text().await.expect(\"read body failed\")"
                    )),
                    HttpResponseMethodKind::Json => Ok(format!(
                        "serde_json::from_str::<f64>(({r}).text().await.expect(\"read body failed\").trim()).expect(\"response.json: expected JSON number\")"
                    )),
                }
            }
            IRExpr::ReaderRead {
                reader_slot: Some(slot),
                ..
            } => Ok(format!(
                "(match __ts2rs_stream_{slot}.next().await {{ std::option::Option::None => __Ts2rsStreamReadResult {{ done: true, value: std::vec::Vec::new() }}, std::option::Option::Some(std::result::Result::Ok(b)) => __Ts2rsStreamReadResult {{ done: false, value: b.to_vec() }}, std::option::Option::Some(std::result::Result::Err(_e)) => panic!(\"read body failed\") }})"
            )),
            IRExpr::ReaderRead { span, .. } => Err(diag(
                f.cm.as_ref(),
                &f.source_path,
                *span,
                "internal error: reader stream slot missing in codegen",
            )),
            _ => {
                let inner = emit_expr(arg, f, stmt_level, module)?;
                Ok(format!("({inner}).await"))
            }
        },
    }
}

fn fetch_init_needs_some(init: &Option<FetchInit>) -> bool {
    init.as_ref()
        .is_some_and(|i| i.method.is_some() || !i.headers.is_empty() || i.body.is_some())
}

fn emit_fetch_call(
    url: &IRExpr,
    init: &Option<FetchInit>,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    let u = emit_expr(url, f, stmt_level, module)?;
    if !fetch_init_needs_some(init) {
        return Ok(format!("__ts2rs_fetch({u}, std::option::Option::None)"));
    }
    let i = init.as_ref().expect("checked");
    let method = i.method.clone().unwrap_or_else(|| "GET".to_string());
    let mut header_parts = Vec::with_capacity(i.headers.len());
    for (k, v) in &i.headers {
        header_parts.push(format!("({:?}.to_string(), {:?}.to_string())", k, v));
    }
    let headers_joined = header_parts.join(", ");
    let body_rust = match &i.body {
        None => "std::option::Option::None".to_string(),
        Some(b) => {
            let be = emit_expr(b, f, stmt_level, module)?;
            format!("std::option::Option::Some(({be}).to_string())")
        }
    };
    Ok(format!(
        "__ts2rs_fetch({u}, std::option::Option::Some(__Ts2rsFetchInit {{ method: {:?}.to_string(), headers: vec![{headers_joined}], body: {body_rust} }}))",
        method
    ))
}

fn emit_string_method_builtin(
    kind: &StringMethodKind,
    receiver: &IRExpr,
    args: &[IRExpr],
    _span: Span,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    let recv = emit_expr(receiver, f, stmt_level, module)?;
    use StringMethodKind::*;
    match kind {
        CharAt => {
            let i = emit_expr(&args[0], f, stmt_level, module)?;
            Ok(format!(
                "({{ let __s = &({recv}); let __ii = ({i}) as i32; let __v: Vec<u16> = __s.encode_utf16().collect(); let __len = __v.len() as i32; let __j = if __ii < 0 {{ __len + __ii }} else {{ __ii }}; if __j < 0 || __j >= __len {{ String::new() }} else {{ String::from_utf16_lossy(&[__v[__j as usize]]) }} }})"
            ))
        }
        CharCodeAt => {
            let i = emit_expr(&args[0], f, stmt_level, module)?;
            Ok(format!(
                "({{ let __s = &({recv}); let __ii = ({i}) as i32; let __v: Vec<u16> = __s.encode_utf16().collect(); let __len = __v.len() as i32; let __j = if __ii < 0 {{ __len + __ii }} else {{ __ii }}; if __j < 0 || __j >= __len {{ 0.0_f64 }} else {{ __v[__j as usize] as f64 }} }})"
            ))
        }
        Slice => {
            let a0 = emit_expr(&args[0], f, stmt_level, module)?;
            if args.len() == 1 {
                Ok(format!(
                    "__ts2rs_utf16_slice(&({recv}), ({a0}) as i32, None, false)"
                ))
            } else {
                let a1 = emit_expr(&args[1], f, stmt_level, module)?;
                Ok(format!(
                    "__ts2rs_utf16_slice(&({recv}), ({a0}) as i32, Some(({a1}) as i32), false)"
                ))
            }
        }
        Substring => {
            let a0 = emit_expr(&args[0], f, stmt_level, module)?;
            if args.len() == 1 {
                Ok(format!(
                    "__ts2rs_utf16_slice(&({recv}), ({a0}) as i32, None, true)"
                ))
            } else {
                let a1 = emit_expr(&args[1], f, stmt_level, module)?;
                Ok(format!(
                    "__ts2rs_utf16_slice(&({recv}), ({a0}) as i32, Some(({a1}) as i32), true)"
                ))
            }
        }
        IndexOf => {
            let needle = emit_expr(&args[0], f, stmt_level, module)?;
            let from = if args.len() == 1 {
                "0i32".to_string()
            } else {
                emit_expr(&args[1], f, stmt_level, module)?
            };
            Ok(format!(
                "__ts2rs_utf16_index_of(&({recv}), &({needle}), ({from}) as i32)"
            ))
        }
        Includes => {
            let needle = emit_expr(&args[0], f, stmt_level, module)?;
            let from = if args.len() == 1 {
                "0i32".to_string()
            } else {
                emit_expr(&args[1], f, stmt_level, module)?
            };
            Ok(format!(
                "(__ts2rs_utf16_index_of(&({recv}), &({needle}), ({from}) as i32) >= 0.0)"
            ))
        }
    }
}

fn emit_seq_expr(
    exprs: &[IRExpr],
    span: Span,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    if exprs.is_empty() {
        return Err(diag(f.cm.as_ref(), &f.source_path, span, "empty sequence"));
    }
    if exprs.len() == 1 {
        return emit_expr(&exprs[0], f, stmt_level, module);
    }
    let inner = indent(stmt_level + 1);
    let close = indent(stmt_level);
    let mut block = String::new();
    block.push_str("({\n");
    for e in &exprs[..exprs.len() - 1] {
        block.push_str(&inner);
        block.push_str(&emit_expr_stmt(e, f, stmt_level, module)?);
        block.push_str(";\n");
    }
    block.push_str(&inner);
    block.push_str(&emit_expr(&exprs[exprs.len() - 1], f, stmt_level, module)?);
    block.push('\n');
    block.push_str(&close);
    block.push_str("})");
    Ok(block)
}

fn emit_tpl(
    parts: &[TplPart],
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    if parts.is_empty() {
        return Ok("\"\".to_string()".to_string());
    }
    if parts.len() == 1 {
        if let TplPart::Static(s) = &parts[0] {
            return Ok(format!("{:?}.to_string()", s));
        }
    }
    let mut fmt = String::new();
    let mut args: Vec<String> = Vec::new();
    for p in parts {
        match p {
            TplPart::Static(s) => {
                for ch in s.chars() {
                    match ch {
                        '{' => fmt.push_str("{{"),
                        '}' => fmt.push_str("}}"),
                        _ => fmt.push(ch),
                    }
                }
            }
            TplPart::Interp(e) => {
                fmt.push_str("{}");
                args.push(emit_expr(e, f, stmt_level, module)?);
            }
        }
    }
    let fmt_esc = fmt.replace('\\', "\\\\").replace('"', "\\\"");
    if args.is_empty() {
        return Ok(format!("format!(\"{fmt_esc}\")"));
    }
    Ok(format!("format!(\"{fmt_esc}\", {})", args.join(", ")))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::build::build_module;
    use crate::sem::check_module;
    use ts2rs_parser::parse_typescript_file;

    #[test]
    fn emit_rust_contains_ts_main_and_println() {
        let src = r#"function main(): number { return 42; }"#;
        let p = parse_typescript_file("t.ts", src).unwrap();
        let mut m = build_module(&p.program, &p.source_map, "t.ts", Some(&p.comments)).unwrap();
        check_module(&mut m).unwrap();
        let rs = emit_rust_with_options(&m, &CodegenOptions::default()).unwrap();
        assert!(rs.contains("fn ts_main"), "{rs}");
        assert!(rs.contains("println!"), "{rs}");
    }

    #[test]
    fn emit_rust_stdlib_helpers_when_needed() {
        let src = r#"function main(): number {
  return "ab".slice(0, 1).length + JSON.stringify(1).length;
}"#;
        let p = parse_typescript_file("t.ts", src).unwrap();
        let mut m = build_module(&p.program, &p.source_map, "t.ts", Some(&p.comments)).unwrap();
        check_module(&mut m).unwrap();
        let rs = emit_rust_with_options(&m, &CodegenOptions::default()).unwrap();
        assert!(rs.contains("__ts2rs_utf16_slice"), "{rs}");
        assert!(rs.contains("__ts2rs_json_escape_string"), "{rs}");
    }

    #[test]
    fn emit_ts_source_comments_writes_frozen_leading() {
        let src = r#"// __hdr__
function main(): number {
  // __body__
  let x: number = 1;
  return x;
}
"#;
        let p = parse_typescript_file("t.ts", src).unwrap();
        let mut m = build_module(&p.program, &p.source_map, "t.ts", Some(&p.comments)).unwrap();
        check_module(&mut m).unwrap();
        let opts = CodegenOptions {
            emit_ts_source_comments: true,
            ..Default::default()
        };
        let rs = emit_rust_with_options(&m, &opts).unwrap();
        assert!(
            rs.contains("// __hdr__"),
            "expected function-level TS comment in Rust: {rs}"
        );
        assert!(
            rs.contains("// __body__"),
            "expected statement-level TS comment in Rust: {rs}"
        );
    }
}
