//! HIR → Rust 源码。

use crate::error::{diag, CompileError};
use crate::ir::*;
use swc_common::Span;

mod helpers;

/// 代码生成选项（默认不改变既有输出）。
#[derive(Debug, Clone, Default)]
pub struct CodegenOptions {
    /// 在每条语句前写入 `// ts: path:line:col`（与诊断格式一致）。
    pub span_comments: bool,
}

pub fn emit_rust(module: &IRModule) -> Result<String, CompileError> {
    emit_rust_with_options(module, &CodegenOptions::default())
}

pub fn emit_rust_with_options(
    module: &IRModule,
    opts: &CodegenOptions,
) -> Result<String, CompileError> {
    let mut out = String::new();
    out.push_str("// Generated by ts2rs — do not edit by hand.\n\n");

    if module_needs_fetch_helper(module) {
        out.push_str(
            "async fn __ts2rs_fetch_text(url: String) -> String {\n    reqwest::get(url.as_str())\n        .await\n        .expect(\"HTTP GET failed\")\n        .text()\n        .await\n        .expect(\"read response body failed\")\n}\n\n",
        );
    }

    for c in &module.classes {
        let trait_name = format!("{}Dyn", c.name);
        let struct_name = format!("{}Obj", c.name);
        out.push_str(&format!("trait {trait_name} {{\n"));
        out.push_str("    fn __class_name(&self) -> &'static str;\n");
        out.push_str("}\n");
        out.push_str(&format!(
            "struct {struct_name} {{ data: std::collections::HashMap<String, i32> }}\n"
        ));
        out.push_str(&format!("impl {trait_name} for {struct_name} {{\n"));
        out.push_str("    fn __class_name(&self) -> &'static str {\n");
        out.push_str(&format!("        \"{}\"\n", c.name));
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    let main_fn = module
        .fns
        .iter()
        .find(|f| f.name == "main")
        .expect("sem ensures main exists");

    for f in &module.fns {
        emit_fn(&mut out, f, 0, opts, module)?;
    }

    if main_fn.is_async {
        out.push_str("#[tokio::main]\nasync fn main() {\n");
    } else {
        out.push_str("fn main() {\n");
    }
    let ret_ty = rust_ty(&main_fn.ret, main_fn)?;
    let await_main = if main_fn.is_async { ".await" } else { "" };
    match ret_ty {
        "()" => {
            out.push_str(&format!("    ts_main(){await_main};\n"));
        }
        "i32" | "bool" | "String" => {
            out.push_str(&format!("    println!(\"{{}}\", ts_main(){await_main});\n"));
        }
        "Vec<i32>" | "std::collections::HashMap<String, i32>" => {
            out.push_str(&format!(
                "    println!(\"{{:?}}\", ts_main(){await_main});\n"
            ));
        }
        _ => {
            return Err(diag(
                main_fn.cm.as_ref(),
                &main_fn.source_path,
                main_fn.span,
                "unexpected return type classification in codegen",
            ));
        }
    }
    out.push_str("}\n");

    Ok(out)
}

fn module_needs_fetch_helper(module: &IRModule) -> bool {
    module.fns.iter().any(|f| stmts_maybe_fetch(&f.body))
}

fn stmts_maybe_fetch(stmts: &[IRStmt]) -> bool {
    stmts.iter().any(stmt_maybe_fetch)
}

fn stmt_maybe_fetch(s: &IRStmt) -> bool {
    match s {
        IRStmt::Let { init, .. } => init.as_ref().is_some_and(expr_maybe_fetch),
        IRStmt::Assign { rhs, .. } | IRStmt::MemberAssign { rhs, .. } => expr_maybe_fetch(rhs),
        IRStmt::Expr { expr, .. } => expr_maybe_fetch(expr),
        IRStmt::Return { arg, .. } => arg.as_ref().is_some_and(expr_maybe_fetch),
        IRStmt::Block { stmts, .. } => stmts_maybe_fetch(stmts),
        IRStmt::If {
            cond,
            then_b,
            else_b,
            ..
        } => {
            expr_maybe_fetch(cond)
                || stmts_maybe_fetch(then_b)
                || else_b.as_deref().is_some_and(stmts_maybe_fetch)
        }
        IRStmt::While { cond, body, .. } => expr_maybe_fetch(cond) || stmts_maybe_fetch(body),
        IRStmt::ForIn { target, body, .. } => expr_maybe_fetch(target) || stmts_maybe_fetch(body),
        IRStmt::DoWhile { body, cond, .. } => stmts_maybe_fetch(body) || expr_maybe_fetch(cond),
        IRStmt::FnDecl { func, .. } => stmts_maybe_fetch(&func.body),
        _ => false,
    }
}

fn expr_maybe_fetch(e: &IRExpr) -> bool {
    match e {
        IRExpr::FetchText { .. } => true,
        IRExpr::Await { arg, .. } => expr_maybe_fetch(arg),
        IRExpr::Binary { left, right, .. } => expr_maybe_fetch(left) || expr_maybe_fetch(right),
        IRExpr::Unary { arg, .. } => expr_maybe_fetch(arg),
        IRExpr::Call { args, .. }
        | IRExpr::MethodCall { args, .. }
        | IRExpr::BuiltinLog { args, .. }
        | IRExpr::MathBuiltin { args, .. } => args.iter().any(expr_maybe_fetch),
        IRExpr::Conditional {
            test, cons, alt, ..
        } => expr_maybe_fetch(test) || expr_maybe_fetch(cons) || expr_maybe_fetch(alt),
        IRExpr::Seq { exprs, .. } => exprs.iter().any(expr_maybe_fetch),
        IRExpr::Tpl { parts, .. } => parts.iter().any(|p| match p {
            TplPart::Interp(x) => expr_maybe_fetch(x),
            TplPart::Static(_) => false,
        }),
        IRExpr::Member { obj, .. } | IRExpr::OptionalMember { obj, .. } => expr_maybe_fetch(obj),
        IRExpr::NullishCoalesce { left, right, .. } => {
            expr_maybe_fetch(left) || expr_maybe_fetch(right)
        }
        IRExpr::ArrayLit { elems, .. } => elems.iter().any(expr_maybe_fetch),
        IRExpr::ObjectLit { fields, .. } => fields.iter().any(|(_, v)| expr_maybe_fetch(v)),
        IRExpr::Index { obj, index, .. } => expr_maybe_fetch(obj) || expr_maybe_fetch(index),
        IRExpr::ArrowFn { body, .. } => stmts_maybe_fetch(body),
        _ => false,
    }
}

fn rust_fn_name(name: &str) -> &str {
    helpers::rust_fn_name(name)
}

fn is_numberish(t: &TsType) -> bool {
    helpers::is_numberish(t)
}

fn rust_ty(t: &TsType, f: &IRFunction) -> Result<&'static str, CompileError> {
    helpers::rust_ty(t, f)
}

fn emit_fn(
    out: &mut String,
    f: &IRFunction,
    level: usize,
    opts: &CodegenOptions,
    module: &IRModule,
) -> Result<(), CompileError> {
    if !f.type_params.is_empty() {
        return Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            f.span,
            format!(
                "internal error: generic function `{}` must be monomorphized before codegen",
                f.name
            ),
        ));
    }
    let ind = indent(level);
    let name = rust_fn_name(&f.name);
    out.push_str(&ind);
    if f.is_async {
        out.push_str("async ");
    }
    out.push_str("fn ");
    out.push_str(name);
    out.push('(');
    for (i, (p, ty)) in f.params.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(p);
        out.push_str(": ");
        out.push_str(rust_ty(ty, f)?);
    }
    out.push_str(") -> ");
    out.push_str(rust_ty(&f.ret, f)?);
    out.push_str(" {\n");
    for s in &f.body {
        emit_stmt(out, s, level + 1, f, opts, module)?;
    }
    out.push_str(&ind);
    out.push_str("}\n");
    if level == 0 {
        out.push('\n');
    }
    Ok(())
}

fn indent(n: usize) -> String {
    helpers::indent(n)
}

fn stmt_span(s: &IRStmt) -> Span {
    helpers::stmt_span(s)
}

fn emit_ts_span_comment(out: &mut String, ind: &str, f: &IRFunction, span: Span) {
    helpers::emit_ts_span_comment(out, ind, f, span);
}

fn emit_stmt(
    out: &mut String,
    s: &IRStmt,
    level: usize,
    f: &IRFunction,
    opts: &CodegenOptions,
    module: &IRModule,
) -> Result<(), CompileError> {
    let ind = indent(level);
    if opts.span_comments && !matches!(s, IRStmt::Empty { .. }) {
        emit_ts_span_comment(out, &ind, f, stmt_span(s));
    }
    match s {
        IRStmt::Empty { .. } => {}
        IRStmt::Let {
            name,
            ty,
            init,
            mutable,
            ..
        } => {
            out.push_str(&ind);
            if *mutable {
                out.push_str("let mut ");
            } else {
                out.push_str("let ");
            }
            out.push_str(name);
            out.push_str(": ");
            out.push_str(rust_ty(ty, f)?);
            if let Some(init_e) = init {
                out.push_str(" = ");
                out.push_str(&emit_expr(init_e, f, level, module)?);
            }
            out.push_str(";\n");
        }
        IRStmt::Assign { name, rhs, .. } => {
            out.push_str(&ind);
            out.push_str(name);
            out.push_str(" = ");
            out.push_str(&emit_expr(rhs, f, level, module)?);
            out.push_str(";\n");
        }
        IRStmt::MemberAssign { obj, prop, rhs, .. } => {
            out.push_str(&ind);
            out.push_str(obj);
            out.push_str(".insert(");
            out.push_str(&format!("{prop:?}.to_string(), "));
            out.push_str(&emit_expr(rhs, f, level, module)?);
            out.push_str(");\n");
        }
        IRStmt::Expr { expr, .. } => {
            out.push_str(&ind);
            out.push_str(&emit_expr_stmt(expr, f, level, module)?);
            out.push_str(";\n");
        }
        IRStmt::Return { arg, .. } => {
            out.push_str(&ind);
            out.push_str("return ");
            if let Some(e) = arg {
                out.push_str(&emit_expr(e, f, level, module)?);
            }
            out.push_str(";\n");
        }
        IRStmt::Block { stmts, .. } => {
            out.push_str(&ind);
            out.push_str("{\n");
            for x in stmts {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::If {
            cond,
            cond_ty,
            then_b,
            else_b,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("if ");
            let c = emit_expr(cond, f, level, module)?;
            if is_numberish(cond_ty) {
                out.push_str(&format!("({c}) != 0"));
            } else {
                out.push_str(&format!("({c})"));
            }
            out.push_str(" {\n");
            for x in then_b {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push('}');
            if let Some(else_b) = else_b {
                out.push_str(" else {\n");
                for x in else_b {
                    emit_stmt(out, x, level + 1, f, opts, module)?;
                }
                out.push_str(&ind);
                out.push_str("}\n");
            } else {
                out.push('\n');
            }
        }
        IRStmt::While {
            cond,
            cond_ty,
            body,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("while ");
            let c = emit_expr(cond, f, level, module)?;
            if is_numberish(cond_ty) {
                out.push_str(&format!("({c}) != 0"));
            } else {
                out.push_str(&format!("({c})"));
            }
            out.push_str(" {\n");
            for x in body {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::ForIn {
            key,
            key_ty,
            target,
            kind,
            body,
            span,
        } => {
            let t = emit_expr(target, f, level, module)?;
            let key_rust_ty = rust_ty(key_ty, f)?;
            let tmp = format!("__forin_target_{}", span.lo.0);
            out.push_str(&ind);
            out.push_str(&format!("let {tmp} = {t};\n"));
            match kind {
                Some(ForInKind::ObjectKeys) => {
                    out.push_str(&ind);
                    out.push_str(&format!("for __k in {tmp}.keys() {{\n"));
                    out.push_str(&indent(level + 1));
                    out.push_str(&format!("let {key}: {key_rust_ty} = __k.clone();\n"));
                }
                Some(ForInKind::ArrayIndices) => {
                    out.push_str(&ind);
                    out.push_str(&format!("for __i in 0..{tmp}.len() {{\n"));
                    out.push_str(&indent(level + 1));
                    out.push_str(&format!("let {key}: {key_rust_ty} = __i.to_string();\n"));
                }
                None => {
                    return Err(diag(
                        f.cm.as_ref(),
                        &f.source_path,
                        *span,
                        "for..in kind missing from sem",
                    ));
                }
            }
            for x in body {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::DoWhile {
            body,
            cond,
            cond_ty,
            ..
        } => {
            out.push_str(&ind);
            out.push_str("loop {\n");
            for x in body {
                emit_stmt(out, x, level + 1, f, opts, module)?;
            }
            let c = emit_expr(cond, f, level, module)?;
            out.push_str(&indent(level + 1));
            if is_numberish(cond_ty) {
                out.push_str(&format!("if ({c}) == 0 {{ break; }}\n"));
            } else {
                out.push_str(&format!("if !({c}) {{ break; }}\n"));
            }
            out.push_str(&ind);
            out.push_str("}\n");
        }
        IRStmt::Break { .. } => {
            out.push_str(&ind);
            out.push_str("break;\n");
        }
        IRStmt::Continue { .. } => {
            out.push_str(&ind);
            out.push_str("continue;\n");
        }
        IRStmt::FnDecl { func, .. } => {
            emit_fn(out, func, level, opts, module)?;
        }
    }
    Ok(())
}

fn emit_expr_stmt(
    e: &IRExpr,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    match e {
        IRExpr::BuiltinLog { args, stderr, .. } => {
            emit_builtin_log(args, f, stmt_level, *stderr, module)
        }
        _ => emit_expr(e, f, stmt_level, module),
    }
}

fn emit_builtin_log(
    args: &[IRExpr],
    f: &IRFunction,
    stmt_level: usize,
    to_stderr: bool,
    module: &IRModule,
) -> Result<String, CompileError> {
    let mac = if to_stderr { "eprintln!" } else { "println!" };
    if args.is_empty() {
        return Ok(format!("{mac}()"));
    }
    let mut parts = Vec::new();
    for a in args {
        parts.push(emit_expr(a, f, stmt_level, module)?);
    }
    if parts.len() == 1 {
        return Ok(format!("{mac}(\"{{}}\", {})", parts[0]));
    }
    let fmt_str = std::iter::repeat("{}")
        .take(parts.len())
        .collect::<Vec<_>>()
        .join(" ");
    let joined = parts.join(", ");
    Ok(format!("{mac}(\"{fmt_str}\", {joined})"))
}

fn emit_expr(
    e: &IRExpr,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    match e {
        IRExpr::Number(n, _) => Ok(format!("{n}")),
        IRExpr::Bool(b, _) => Ok(format!("{b}")),
        IRExpr::Str(s, _) => Ok(format!("{:?}.to_string()", s)),
        IRExpr::Null(_) | IRExpr::Undefined(_) => Ok("()".to_string()),
        IRExpr::This(_) => Ok("__self".to_string()),
        IRExpr::Super(_) => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            f.span,
            "`super` expression cannot be emitted directly",
        )),
        IRExpr::Ident(name, _) => Ok(name.clone()),
        IRExpr::Unary { op, arg, .. } => {
            let a = emit_expr(arg, f, stmt_level, module)?;
            match op {
                IRUnaryOp::Neg => Ok(format!("(-({a}))")),
                IRUnaryOp::Not => Ok(format!("!({a})")),
            }
        }
        IRExpr::Binary {
            op,
            left,
            right,
            kind,
            span,
        } => {
            let l = emit_expr(left, f, stmt_level, module)?;
            let r = emit_expr(right, f, stmt_level, module)?;
            use IRBinOp::*;
            let mid = match op {
                Add => {
                    if matches!(kind, Some(BinaryKind::StrConcat)) {
                        format!("format!(\"{{}}{{}}\", {l}, {r})")
                    } else {
                        format!("({l} + {r})")
                    }
                }
                Sub => format!("({l} - {r})"),
                Mul => format!("({l} * {r})"),
                Div => format!("({l} / {r})"),
                Eq => format!("({l} == {r})"),
                Ne => format!("({l} != {r})"),
                Lt => format!("({l} < {r})"),
                Le => format!("({l} <= {r})"),
                Gt => format!("({l} > {r})"),
                Ge => format!("({l} >= {r})"),
                LogicalAnd | LogicalOr => {
                    let (lhs_n, rhs_n) = match kind {
                        Some(BinaryKind::Logical {
                            lhs_number_truthy,
                            rhs_number_truthy,
                        }) => (*lhs_number_truthy, *rhs_number_truthy),
                        _ => {
                            return Err(diag(
                                f.cm.as_ref(),
                                &f.source_path,
                                *span,
                                "`&&` / `||` missing Logical kind (semantic pass bug)",
                            ));
                        }
                    };
                    let ls = if lhs_n { format!("({l} != 0)") } else { l };
                    let rs = if rhs_n { format!("({r} != 0)") } else { r };
                    match op {
                        LogicalAnd => format!("({ls} && {rs})"),
                        LogicalOr => format!("({ls} || {rs})"),
                        _ => unreachable!(),
                    }
                }
            };
            Ok(mid)
        }
        IRExpr::Call { callee, args, .. } => {
            let name = rust_fn_name(callee);
            let mut a = Vec::new();
            for x in args {
                a.push(emit_expr(x, f, stmt_level, module)?);
            }
            Ok(format!("{}({})", name, a.join(", ")))
        }
        IRExpr::ArrowFn {
            params, ret, body, ..
        } => {
            if params.len() != 1 || !is_numberish(&params[0].1) || !is_numberish(ret) {
                return Err(diag(
                    f.cm.as_ref(),
                    &f.source_path,
                    f.span,
                    "current closure codegen supports only `(number) => number`",
                ));
            }
            let (pname, pty) = &params[0];
            let mut body_out = String::new();
            for s in body {
                emit_stmt(
                    &mut body_out,
                    s,
                    stmt_level + 1,
                    f,
                    &CodegenOptions::default(),
                    module,
                )?;
            }
            Ok(format!(
                "std::rc::Rc::new(move |{}: {}| -> {} {{\n{}{} }})",
                pname,
                rust_ty(pty, f)?,
                rust_ty(ret, f)?,
                body_out,
                indent(stmt_level)
            ))
        }
        IRExpr::MethodCall {
            receiver,
            method,
            args,
            ..
        } => {
            let name = rust_fn_name(method);
            let mut a = vec![emit_expr(receiver, f, stmt_level, module)?];
            for x in args {
                a.push(emit_expr(x, f, stmt_level, module)?);
            }
            Ok(format!("{}({})", name, a.join(", ")))
        }
        IRExpr::BuiltinLog { span, .. } => Err(diag(
            f.cm.as_ref(),
            &f.source_path,
            *span,
            "console.log / console.error / console.debug must be in expression statement position",
        )),
        IRExpr::Conditional {
            test,
            cons,
            alt,
            cond_ty,
            span,
            ..
        } => {
            let ct = cond_ty.as_ref().ok_or_else(|| {
                diag(
                    f.cm.as_ref(),
                    &f.source_path,
                    *span,
                    "ternary condition type not filled by sem",
                )
            })?;
            let c = emit_expr(test, f, stmt_level, module)?;
            let cond_s = if is_numberish(ct) {
                format!("({c}) != 0")
            } else {
                format!("({c})")
            };
            let t = emit_expr(cons, f, stmt_level, module)?;
            let a = emit_expr(alt, f, stmt_level, module)?;
            Ok(format!("(if {cond_s} {{ {t} }} else {{ {a} }})"))
        }
        IRExpr::Seq { exprs, span } => emit_seq_expr(exprs, *span, f, stmt_level, module),
        IRExpr::Tpl { parts, .. } => emit_tpl(parts, f, stmt_level, module),
        IRExpr::Member {
            obj,
            prop,
            length_dispatch,
            ..
        } => {
            let o = emit_expr(obj, f, stmt_level, module)?;
            if prop == "length" {
                match length_dispatch {
                    Some(MemberLengthDispatch::JsStringUtf16) => {
                        Ok(format!("(({o}.encode_utf16().count()) as i32)"))
                    }
                    Some(MemberLengthDispatch::VecLen) => Ok(format!("({o}.len() as i32)")),
                    None => Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop)),
                }
            } else {
                Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop))
            }
        }
        IRExpr::OptionalMember {
            obj,
            prop,
            length_dispatch,
            ..
        } => match &**obj {
            IRExpr::Null(_) | IRExpr::Undefined(_) => Ok("()".to_string()),
            _ => {
                let o = emit_expr(obj, f, stmt_level, module)?;
                if prop == "length" {
                    match length_dispatch {
                        Some(MemberLengthDispatch::JsStringUtf16) => {
                            Ok(format!("(({o}.encode_utf16().count()) as i32)"))
                        }
                        Some(MemberLengthDispatch::VecLen) => Ok(format!("({o}.len() as i32)")),
                        None => Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop)),
                    }
                } else {
                    Ok(format!("(*{o}.get({:?}).expect(\"missing field\"))", prop))
                }
            }
        },
        IRExpr::MathBuiltin { kind, args, .. } => {
            use MathBuiltinKind::*;
            match kind {
                Abs => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("(({a}) as i32).abs()"))
                }
                Min => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    let b = emit_expr(&args[1], f, stmt_level, module)?;
                    Ok(format!("(({a}) as i32).min(({b}) as i32)"))
                }
                Max => {
                    let a = emit_expr(&args[0], f, stmt_level, module)?;
                    let b = emit_expr(&args[1], f, stmt_level, module)?;
                    Ok(format!("(({a}) as i32).max(({b}) as i32)"))
                }
                Floor | Ceil => {
                    let n = emit_expr(&args[0], f, stmt_level, module)?;
                    Ok(format!("({n})"))
                }
            }
        }
        IRExpr::NullishCoalesce { left, right, .. } => {
            if matches!(&**left, IRExpr::Null(_) | IRExpr::Undefined(_)) {
                emit_expr(right, f, stmt_level, module)
            } else {
                emit_expr(left, f, stmt_level, module)
            }
        }
        IRExpr::ArrayLit { elems, .. } => {
            let mut xs = Vec::with_capacity(elems.len());
            for e in elems {
                xs.push(emit_expr(e, f, stmt_level, module)?);
            }
            Ok(format!("vec![{}]", xs.join(", ")))
        }
        IRExpr::ObjectLit { fields, .. } => {
            if fields.is_empty() {
                return Ok("std::collections::HashMap::new()".to_string());
            }
            let mut pairs = Vec::with_capacity(fields.len());
            for (k, v) in fields {
                pairs.push(format!(
                    "({:?}.to_string(), {})",
                    k,
                    emit_expr(v, f, stmt_level, module)?
                ));
            }
            Ok(format!(
                "std::collections::HashMap::from([{}])",
                pairs.join(", ")
            ))
        }
        IRExpr::Index { obj, index, .. } => {
            let o = emit_expr(obj, f, stmt_level, module)?;
            let i = emit_expr(index, f, stmt_level, module)?;
            Ok(format!("({o}[({i}) as usize])"))
        }
        IRExpr::FetchText { url, .. } => {
            let u = emit_expr(url, f, stmt_level, module)?;
            Ok(format!("__ts2rs_fetch_text({u})"))
        }
        IRExpr::Await { arg, .. } => {
            let inner = emit_expr(arg, f, stmt_level, module)?;
            Ok(format!("({inner}).await"))
        }
    }
}

fn emit_seq_expr(
    exprs: &[IRExpr],
    span: Span,
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    if exprs.is_empty() {
        return Err(diag(f.cm.as_ref(), &f.source_path, span, "empty sequence"));
    }
    if exprs.len() == 1 {
        return emit_expr(&exprs[0], f, stmt_level, module);
    }
    let inner = indent(stmt_level + 1);
    let close = indent(stmt_level);
    let mut block = String::new();
    block.push_str("({\n");
    for e in &exprs[..exprs.len() - 1] {
        block.push_str(&inner);
        block.push_str(&emit_expr_stmt(e, f, stmt_level, module)?);
        block.push_str(";\n");
    }
    block.push_str(&inner);
    block.push_str(&emit_expr(&exprs[exprs.len() - 1], f, stmt_level, module)?);
    block.push('\n');
    block.push_str(&close);
    block.push_str("})");
    Ok(block)
}

fn emit_tpl(
    parts: &[TplPart],
    f: &IRFunction,
    stmt_level: usize,
    module: &IRModule,
) -> Result<String, CompileError> {
    if parts.is_empty() {
        return Ok("\"\".to_string()".to_string());
    }
    if parts.len() == 1 {
        if let TplPart::Static(s) = &parts[0] {
            return Ok(format!("{:?}.to_string()", s));
        }
    }
    let mut fmt = String::new();
    let mut args: Vec<String> = Vec::new();
    for p in parts {
        match p {
            TplPart::Static(s) => {
                for ch in s.chars() {
                    match ch {
                        '{' => fmt.push_str("{{"),
                        '}' => fmt.push_str("}}"),
                        _ => fmt.push(ch),
                    }
                }
            }
            TplPart::Interp(e) => {
                fmt.push_str("{}");
                args.push(emit_expr(e, f, stmt_level, module)?);
            }
        }
    }
    let fmt_esc = fmt.replace('\\', "\\\\").replace('"', "\\\"");
    if args.is_empty() {
        return Ok(format!("format!(\"{fmt_esc}\")"));
    }
    Ok(format!("format!(\"{fmt_esc}\", {})", args.join(", ")))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::build::build_module;
    use crate::sem::check_module;
    use ts2rs_parser::parse_typescript_file;

    #[test]
    fn emit_rust_contains_ts_main_and_println() {
        let src = r#"function main(): number { return 42; }"#;
        let p = parse_typescript_file("t.ts", src).unwrap();
        let mut m = build_module(&p.program, &p.source_map, "t.ts").unwrap();
        check_module(&mut m).unwrap();
        let rs = emit_rust_with_options(&m, &CodegenOptions::default()).unwrap();
        assert!(rs.contains("fn ts_main"), "{rs}");
        assert!(rs.contains("println!"), "{rs}");
    }
}
